#pragma checksum "E:\VS2012\MSpace\MSpace\Views\Global\Outline.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "91B8F884E595CE9285CF404E097CA85E03366823"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using MSpace.Models;
    
    
    public class _Page_Views_Global_Outline_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden

        
        public _Page_Views_Global_Outline_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

            
            #line 1 "E:\VS2012\MSpace\MSpace\Views\Global\Outline.cshtml"
  
    ViewBag.Title = "Outline";


            
            #line default
            #line hidden
WriteLiteral("\r\n    <ul class=\"nav pull-right\">\r\n        <li><a href=\"");


            
            #line 6 "E:\VS2012\MSpace\MSpace\Views\Global\Outline.cshtml"
                Write(Url.RouteUrl("DefaultRoute", new { controller = "User", action = "Register" }));

            
            #line default
            #line hidden
WriteLiteral("\">注册</a></li>\r\n        <li class=\"divider-vertical\"></li>\r\n        <li><a href=\"");


            
            #line 8 "E:\VS2012\MSpace\MSpace\Views\Global\Outline.cshtml"
                Write(Url.RouteUrl("DefaultRoute", new { controller = "Account", action = "LogOn" }));

            
            #line default
            #line hidden
WriteLiteral("\">登录</a></li>\r\n        ");



WriteLiteral("\r\n    </ul>\r\n");


        }
    }
}
