#pragma checksum "E:\VS2012\MSpace\MSpace\Views\Home\About.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "60402B3685E5753BFA33747DE96B9269DD3A296E"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using MSpace.Models;
    
    
    public class _Page_Views_Home_About_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden

        
        public _Page_Views_Home_About_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

            
            #line 1 "E:\VS2012\MSpace\MSpace\Views\Home\About.cshtml"
  
    ViewBag.Title = "关于 ---- " + ViewBag.AuthorName;


            
            #line default
            #line hidden

DefineSection("scripts", () => {

WriteLiteral("\r\n    <link rel=\"stylesheet\" href=\"");


            
            #line 5 "E:\VS2012\MSpace\MSpace\Views\Home\About.cshtml"
                            Write(Url.Content("~/Content/templates/bootstrap/plugins/datepicker/css/datepicker.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" />\r\n    <script src=\"");


            
            #line 6 "E:\VS2012\MSpace\MSpace\Views\Home\About.cshtml"
            Write(Url.Content("~/Content/templates/bootstrap/plugins/datepicker/js/bootstrap-datepicker.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 7 "E:\VS2012\MSpace\MSpace\Views\Home\About.cshtml"
                                   Write(Url.Content("~/Content/widgets/masonry/jquery.masonry.js"));

            
            #line default
            #line hidden
WriteLiteral("\" ></script>\r\n\r\n    <script type=\"text/javascript\">\r\n        $(function () {\r\n   " +
"         $(\'#navList > li:not(.divider-vertical):eq(1)\').addClass(\'active\').sibl" +
"ings().removeClass(\'active\');\r\n            $(\'.datepicker\').datepicker();\r\n     " +
"       $(\'#nav1 li:eq(0)\').addClass(\'active\');\r\n            $(\'#nav1 li a\').on(\'" +
"click\', function (e) {\r\n                e.preventDefault();\r\n                $(t" +
"his).parent().addClass(\'active\').siblings().removeClass(\'active\');\r\n            " +
"    //art.dialog({\r\n                //    title: \'信息提示\',\r\n                //    " +
"esc: false,\r\n                //    content: $(this).text(),\r\n                // " +
"   width: 350,\r\n                //    height: 150,\r\n                //}).follow(" +
"this);\r\n                var $container = $(\'#infoArea\');\r\n                var $l" +
"oading = $(\'#loading\');\r\n                $.ajax({\r\n                    url: $(th" +
"is).attr(\"href\"),\r\n                    dataType: \'html\',\r\n                    be" +
"foreSend: function (req) {\r\n                        $container.empty();\r\n       " +
"                 $loading.fadeIn(\'fast\');\r\n                    },\r\n             " +
"       error: function (XMLHttpRequest, textStatus, errorThrown) {\r\n            " +
"            // 通常 textStatus 和 errorThrown 之中\r\n                        // 只有一个会包" +
"含信息\r\n                        this; // 调用本次AJAX请求时传递的options参数\r\n                 " +
"   },\r\n                    success: function (data, textStatus, jqXHR) {\r\n      " +
"                  $container.append(data);\r\n                        //doLayout()" +
";\r\n                    },\r\n                    complete: function (XMLHttpReques" +
"t, textStatus) {\r\n                        //this; // 调用本次AJAX请求时传递的options参数\r\n  " +
"                      $loading.fadeOut(\'fast\');\r\n                    }\r\n        " +
"        });\r\n            });\r\n            $(\'#accordion2 a\').bind(\'click\', funct" +
"ion event() {\r\n                event.preventDefault();\r\n                $(this)." +
"parent().addClass(\'active\').siblings().removeClass(\'active\');\r\n            });\r\n" +
"            //art.dialog({\r\n            //    title: \'信息提示\',\r\n            //    " +
"esc: false,\r\n            //    content: \'欢迎来到我的博客\',\r\n            //    width: 35" +
"0 ,\r\n            //    height:150 ,\r\n            //}).time(45000).shake();\r\n    " +
"        $(\'#urlQRCode\').qrcode({\r\n                text: window.location,\r\n      " +
"          width: \"150\",\r\n                height: \"150\"\r\n            }).addClass(" +
"\'img-polaroid\');\r\n            \r\n            $(\'#infoArea\').delegate(\'.map\', \'cli" +
"ck\', function (e) {\r\n                InitializeMap($(this).attr(\'data-val\'));\r\n " +
"               e.preventDefault();\r\n            });\r\n\r\n        });\r\n\r\n        fu" +
"nction doLayout() {\r\n            var $container = $(\'#infoArea\');\n            $c" +
"ontainer.imagesLoaded(function () {\r\n                $container.masonry({\r\n     " +
"               itemSelector: \'item\',\r\n                    columnWidth: 150,\r\n   " +
"                 isAnimated: true\r\n                });\r\n\r\n            });\r\n     " +
"       //$container.masonry(\'layout\');\r\n        }\r\n\r\n    </script>\r\n\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("Login", () => {

WriteLiteral("\r\n     \r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("LeftBanner", () => {

WriteLiteral("\r\n    <div class=\"row-fluid\">\r\n       <div id=\"urlQRCode\" style=\"text-align:cente" +
"r;\" class=\"span12 well\"></div>\r\n    </div>\r\n   ");



WriteLiteral("\r\n\r\n    <div class=\"row-fluid\">\r\n        <ul id=\"nav1\" class=\"nav nav-pills nav-s" +
"tacked\">\r\n            <li>\r\n                <a href=\"");


            
            #line 109 "E:\VS2012\MSpace\MSpace\Views\Home\About.cshtml"
                    Write(Url.Action("Experience","About"));

            
            #line default
            #line hidden
WriteLiteral("\">我的履历</a>\r\n            </li>\r\n            <li>\r\n                <a href=\"");


            
            #line 112 "E:\VS2012\MSpace\MSpace\Views\Home\About.cshtml"
                    Write(Url.Action("Resume","About"));

            
            #line default
            #line hidden
WriteLiteral("\">我的简历</a>\r\n            </li>\r\n            <li><a href=\"");


            
            #line 114 "E:\VS2012\MSpace\MSpace\Views\Home\About.cshtml"
                    Write(Url.Action("Plan","About"));

            
            #line default
            #line hidden
WriteLiteral("\">我的规划</a></li>\r\n        </ul>\r\n    </div>\r\n\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("BreadCrumb", () => {

WriteLiteral("\r\n    <div class=\"span12\">\r\n        <ul class=\"breadcrumb\">\r\n            <li clas" +
"s=\"active\">关于</li>\r\n        </ul>\r\n    </div>\r\n");


});

WriteLiteral("\r\n\r\n\r\n<div class=\"row-fluid\">\r\n    <div class=\"span12\" id=\"infoArea\">\r\n        ");


            
            #line 131 "E:\VS2012\MSpace\MSpace\Views\Home\About.cshtml"
   Write(Html.Action("Index", "About"));

            
            #line default
            #line hidden
WriteLiteral(@"
        
    </div>
</div>


<div class=""row-fluid"">
    <div id=""gdmap"" class=""span12"" style=""height:500px;"" ></div>
</div>

     


<div id=""loading"" style=""display:none;"" class=""row-fluid"">
    <div class=""span12"">
        <div style=""width:150px;margin:0 auto;""><img src=""");


            
            #line 146 "E:\VS2012\MSpace\MSpace\Views\Home\About.cshtml"
                                                     Write(Url.Content("~/Content/loading8.gif"));

            
            #line default
            #line hidden
WriteLiteral("\" /></div>\r\n    </div>\r\n</div>\r\n\r\n\r\n\r\n<script type=\"text/javascript\" src=\"http://" +
"maps.googleapis.com/maps/api/js?libraries=geometry,places&sensor=true&language=z" +
"h-CN\" ></script>\r\n\r\n<script type=\"text/javascript\">\r\n    var map;\r\n    //计算位置的\r\n" +
"    var geocoder = new google.maps.Geocoder();\r\n    function InitializeMap(addre" +
"ss) {\r\n        var myOptions = {\r\n            zoom: 8,\r\n            mapTypeId: g" +
"oogle.maps.MapTypeId.ROADMAP\r\n        };\r\n        map = new google.maps.Map(docu" +
"ment.getElementById(\"gdmap\"), myOptions);\r\n        // Try HTML5 geolocation\r\n   " +
"     //if (navigator.geolocation) {\r\n        //    navigator.geolocation.getCurr" +
"entPosition(function (position) {\r\n        //        var pos = new google.maps.L" +
"atLng(position.coords.latitude,\r\n        //                                     " +
"    position.coords.longitude);\r\n\r\n        //        var infowindow = new google" +
".maps.InfoWindow({\r\n        //            map: map,\r\n        //            posit" +
"ion: pos,\r\n        //            content: \'Location found using HTML5.\'\r\n       " +
" //        });\r\n\r\n        //        map.setCenter(pos);\r\n        //    }, functi" +
"on () {\r\n        //        handleNoGeolocation(true);\r\n        //    });\r\n      " +
"  //} else {\r\n        //    // Browser doesn\'t support Geolocation\r\n        //  " +
"  handleNoGeolocation(false);\r\n        //}\r\n        $(\"html, body\").animate({\r\n " +
"           scrollTop: $(\'#gdmap\').parent().offset().top - 80 + \"px\"\r\n        }, " +
"1000);\r\n        \r\n        //计算位置的\r\n        geocoder.geocode({ \'address\': address" +
" }, function (results, status) {\r\n            if (status == google.maps.Geocoder" +
"Status.OK) {\r\n                map.setCenter(results[0].geometry.location);\r\n    " +
"            var marker = new google.maps.Marker({\r\n                    map: map," +
"\r\n                    position: results[0].geometry.location\r\n                })" +
";\r\n\r\n            }\r\n            else {\r\n                alert(\"Geocode was not s" +
"uccessful for the following reason: \" + status);\r\n            }\r\n        });\r\n\r\n" +
"    }\r\n\r\n    function handleNoGeolocation(errorFlag) {\r\n        if (errorFlag) {" +
"\r\n            var content = \'Error: The Geolocation service failed.\';\r\n        }" +
" else {\r\n            var content = \'Error: Your browser doesn\\\'t support geoloca" +
"tion.\';\r\n        }\r\n\r\n        var options = {\r\n            map: map,\r\n          " +
"  position: new google.maps.LatLng(60, 105),\r\n            content: content\r\n    " +
"    };\r\n\r\n        var infowindow = new google.maps.InfoWindow(options);\r\n       " +
" map.setCenter(options.position);\r\n    }\r\n</script> \r\n\r\n\r\n\r\n");


        }
    }
}
