#pragma checksum "E:\VS2012\MSpace\MSpace\Views\Home\RSS.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "F64B3253F9AF71355DF3342AA7C579A50B2EF621"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using MSpace.Models;
    
    
    public class _Page_Views_Home_RSS_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden

        
        public _Page_Views_Home_RSS_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

            
            #line 1 "E:\VS2012\MSpace\MSpace\Views\Home\RSS.cshtml"
  
    ViewBag.Title = "RSS";


            
            #line default
            #line hidden

DefineSection("scripts", () => {

WriteLiteral("\r\n    <link rel=\"stylesheet\" href=\"");


            
            #line 5 "E:\VS2012\MSpace\MSpace\Views\Home\RSS.cshtml"
                            Write(Url.Content("~/Content/templates/bootstrap/plugins/datepicker/css/datepicker.css"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    <script src=\"");


            
            #line 6 "E:\VS2012\MSpace\MSpace\Views\Home\RSS.cshtml"
            Write(Url.Content("~/Content/templates/bootstrap/plugins/datepicker/js/bootstrap-datepicker.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n\r\n    <script type=\"text/javascript\">\r\n      " +
"  $(function () {\r\n            $(\'#navList > li:not(.divider-vertical):eq(2)\').a" +
"ddClass(\'active\').siblings().removeClass(\'active\');\r\n        });\r\n\r\n    </script" +
">\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("LeftBanner", () => {

WriteLiteral(@"
    <div class=""row-fluid"">
	<div class=""well sidebar-nav"">
		<ul class=""nav nav-list"">
			<li class=""nav-header"">系统信息</li>
			<li class=""active""><a href=""#gallary"">系统展示</a></li>
			<li><a href=""#"">作者信息</a></li>
			<li class=""nav-header"">最新日志</li>
			<li><a href=""log.php?id=1b1b72af-888b-48fe-bdb2-11d09239df1e"">升级到VS2012后遇到的两个问题</a></li>
            <li><a href=""log.php?id=833c2acb-609d-42f9-978c-d4983054ea6a"">adobe</a></li>
            <li><a href=""log.php?id=f4bfa338-4708-442d-8cc0-5ecb086cc24a"">戒指的戴法</a></li>
            <li><a href=""log.php?id=a1cf1884-7c02-470e-80af-dbab660f2e01"">一个男人关心的东西 决定了他的层次</a></li>
            <li><a href=""log.php?id=210ba60d-8a2f-473d-8e07-29ab494cbc62"">多线程加载进度条实例 </a></li>
            <li><a href=""log.php?id=23d1e38e-70ab-48a8-a3f9-2d4b05cfbe58"">程序员为啥就“死的早”呢？</a></li>
            <li><a href=""log.php?id=ab89ec25-4589-4f9b-91dc-6ec91395a6f0"">人大常委会关于加强网络信息保护决定草案(全文)</a></li>
		</ul>
	</div><!--/.well -->
    </div>
");


});

WriteLiteral("\r\n\r\n");


DefineSection("BreadCrumb", () => {

WriteLiteral("\r\n    <div class=\"span12\">\r\n        <ul class=\"breadcrumb\">\r\n            <li>\r\n  " +
"              <a href=\"#\">RSS</a>\r\n            </li>\r\n        </ul>\r\n    </div>\r" +
"\n");


});

WriteLiteral("\r\n\r\n<div class=\"row-fluid\">\r\n    <h2>RSS</h2>\r\n</div>\r\n");


        }
    }
}
