#pragma checksum "E:\VS2012\MSpace\MSpace\Views\Home\Album.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "4EF0B27F433724C00D47CDE57A813A91C661BB59"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using MSpace.Models;
    
    
    public class _Page_Views_Home_Album_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden

        
        public _Page_Views_Home_Album_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

            
            #line 1 "E:\VS2012\MSpace\MSpace\Views\Home\Album.cshtml"
  
    ViewBag.Title = "Album";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("Scripts", () => {

WriteLiteral("\r\n    <link rel=\"stylesheet\" href=\"");


            
            #line 6 "E:\VS2012\MSpace\MSpace\Views\Home\Album.cshtml"
                            Write(Url.Content("~/Content/widgets/masonry/css/style.css"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/css\" />\r\n\r\n    <script src=\"");


            
            #line 8 "E:\VS2012\MSpace\MSpace\Views\Home\Album.cshtml"
            Write(Url.Content("~/Content/widgets/masonry/jquery.masonry.js"));

            
            #line default
            #line hidden
WriteLiteral(@""" type=""text/javascript""></script>
    <script type=""text/javascript"">
        $(function(){
            var $container = $('#container');

            $container.imagesLoaded( function(){
              $container.masonry({
                itemSelector : '.box'
              });
            });
        });
    </script>
");


});

WriteLiteral("\r\n\r\n<div id=\"container\">\r\n        <div class=\"box photo col3\">\r\n      <a href=\"ht" +
"tp://www.flickr.com/photos/nemoorange/5013039951/\" title=\"Stanley by Dave DeSand" +
"ro, on Flickr\"><img src=\"http://farm5.static.flickr.com/4113/5013039951_3a47ccd5" +
"09.jpg\" alt=\"Stanley\" /></a>\r\n    </div>\r\n  \r\n    <div class=\"box photo col3\">\r\n" +
"      <a href=\"http://www.flickr.com/photos/nemoorange/5013039885/\" title=\"Offic" +
"er by Dave DeSandro, on Flickr\"><img src=\"http://farm5.static.flickr.com/4131/50" +
"13039885_0d16ac87bc.jpg\" alt=\"Officer\" /></a>\r\n    </div>\r\n  \r\n    <div class=\"b" +
"ox photo col3\">\r\n      <a href=\"http://www.flickr.com/photos/nemoorange/50130395" +
"83/\" title=\"Tony by Dave DeSandro, on Flickr\"><img src=\"http://farm5.static.flic" +
"kr.com/4086/5013039583_26717f6e89.jpg\" alt=\"Tony\" /></a>\r\n    </div>\r\n  \r\n    <d" +
"iv class=\"box photo col3\">\r\n      <a href=\"http://www.flickr.com/photos/nemooran" +
"ge/5013646070/\" title=\"Kendra by Dave DeSandro, on Flickr\"><img src=\"http://farm" +
"5.static.flickr.com/4146/5013646070_f1f44b1939.jpg\" alt=\"Kendra\" /></a>\r\n    </d" +
"iv>\r\n  \r\n    <div class=\"box photo col3\">\r\n      <a href=\"http://www.flickr.com/" +
"photos/nemoorange/5013039541/\" title=\"Giraffe by Dave DeSandro, on Flickr\"><img " +
"src=\"http://farm5.static.flickr.com/4144/5013039541_17f2579e33.jpg\" alt=\"Giraffe" +
"\" /></a>\r\n    </div>\r\n  \r\n    <div class=\"box photo col3\">\r\n      <a href=\"http:" +
"//www.flickr.com/photos/nemoorange/5013039741/\" title=\"Gavin by Dave DeSandro, o" +
"n Flickr\"><img src=\"http://farm5.static.flickr.com/4153/5013039741_d860fb640b.jp" +
"g\" alt=\"Gavin\" /></a>\r\n    </div>\r\n  \r\n    <div class=\"box photo col3\">\r\n      <" +
"a href=\"http://www.flickr.com/photos/nemoorange/5013039697/\" title=\"Anita by Dav" +
"e DeSandro, on Flickr\"><img src=\"http://farm5.static.flickr.com/4113/5013039697_" +
"a15e41fcd8.jpg\" alt=\"Anita\" /></a>\r\n    </div>\r\n  \r\n    <div class=\"box photo co" +
"l3\">\r\n      <a href=\"http://www.flickr.com/photos/nemoorange/5013646314/\" title=" +
"\"Take My Portrait by Dave DeSandro, on Flickr\"><img src=\"http://farm5.static.fli" +
"ckr.com/4124/5013646314_c7eaf84918.jpg\"   alt=\"Take My Portrait\" /></a>\r\n    </d" +
"iv>\r\n  \r\n    <div class=\"box photo col3\">\r\n      <a href=\"http://www.flickr.com/" +
"photos/nemoorange/5013040075/\" title=\"Wonder by Dave DeSandro, on Flickr\"><img s" +
"rc=\"http://farm5.static.flickr.com/4089/5013040075_bac12ff74e.jpg\" alt=\"Wonder\" " +
"/></a>\r\n    </div>\r\n</div>\r\n");


        }
    }
}
