#pragma checksum "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\PrivateMessage\Read.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "55B9DC848E305E8136C4863BD8257BDA2A143CA1"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    
    
    public class _Page_Areas_Admin_Views_PrivateMessage_Read_cshtml : System.Web.Mvc.WebViewPage<MSpace.Models.PrivateMessage> {
        
#line hidden

        
        public _Page_Areas_Admin_Views_PrivateMessage_Read_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

WriteLiteral("\r\n");


            
            #line 3 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\PrivateMessage\Read.cshtml"
  
    ViewBag.Title = "Read";


            
            #line default
            #line hidden
WriteLiteral("\r\n<h2>Reply</h2>\r\n\r\n<fieldset>\r\n    <legend>PrivateMessage</legend>\r\n        <div" +
" class=\"media\">\r\n            <a class=\"pull-left\" href=\"#\">\r\n                <im" +
"g class=\"media-object\" src=\"http://www.gravatar.com/avatar/");


            
            #line 13 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\PrivateMessage\Read.cshtml"
                                                                         Write(ViewBag.EmailHash);

            
            #line default
            #line hidden
WriteLiteral("?s=75&d=monsterid&r=g\" >\r\n            </a>\r\n            <div class=\"media-body\">\r" +
"\n                <h4 class=\"media-heading\">");


            
            #line 16 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\PrivateMessage\Read.cshtml"
                                     Write(Model.Name);

            
            #line default
            #line hidden
WriteLiteral(" 发表于 ");


            
            #line 16 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\PrivateMessage\Read.cshtml"
                                                     Write(Model.PublishDate);

            
            #line default
            #line hidden
WriteLiteral("</h4>\r\n                <!-- Nested media object -->\r\n                <div class=\"" +
"media lead\">\r\n                     ");


            
            #line 19 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\PrivateMessage\Read.cshtml"
                Write(Model.Content);

            
            #line default
            #line hidden
WriteLiteral(@"
                </div>
            </div>
        </div>
    
</fieldset>


<script type=""text/javascript"">
    $(function () {
        $('#loadReply').click(function (e) {
            e.preventDefault();
            $.ajax({
                url: $(this).attr('href'),
                cache: false,
                type: 'GET',
                dataType: 'JSON',
                success: function () {
                    
                }
            });
        });
    });
</script>

");


DefineSection("LeftFooter", () => {

WriteLiteral("\r\n    <a class=\"win-command\" href=\"");


            
            #line 45 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\PrivateMessage\Read.cshtml"
                            Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <span class=\"win-commandimage win-commandring\">&#xe11f;</span>\r\n     " +
"   <span class=\"win-label\">查看所有私信</span>\r\n    </a>\r\n    <a class=\"win-command\" i" +
"d=\"loadReply\" href=\"");


            
            #line 49 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\PrivateMessage\Read.cshtml"
                                           Write(Url.Action("ListReply","PrivateMessage", new { id = @Model.MessageId}));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <span class=\"win-commandimage win-commandring\">&#x0059;</span>\r\n     " +
"   <span class=\"win-label\">查看所有回复</span>\r\n    </a>\r\n    <a class=\"win-command\" h" +
"ref=\"");


            
            #line 53 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\PrivateMessage\Read.cshtml"
                            Write(Url.Action("Reply","PrivateMessageReply", new { id = @Model.MessageId}));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <span class=\"win-commandimage win-commandring\">&#x0059;</span>\r\n     " +
"   <span class=\"win-label\">回复私信</span>\r\n    </a>\r\n");


});

WriteLiteral("\r\n\r\n\r\n");


        }
    }
}
