#pragma checksum "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "280CD951C46F928941EB8F18074D1BB893547227"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using MSpace.Models;
    
    
    public class _Page_Views_Home_Gallary_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden

        
        public _Page_Views_Home_Gallary_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

            
            #line 1 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
  
    ViewBag.Title = "Gallary";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("scripts", () => {

WriteLiteral("\r\n    <link rel=\"stylesheet\" href=\"");


            
            #line 6 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
                            Write(Url.Content("~/Content/templates/bootstrap/plugins/datepicker/css/datepicker.css"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    <script src=\"");


            
            #line 7 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
            Write(Url.Content("~/Content/templates/bootstrap/plugins/datepicker/js/bootstrap-datepicker.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n\r\n    <link rel=\"stylesheet\" href=\"");


            
            #line 9 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
                            Write(Url.Content("~/Content/widget/iview/iview.css"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    <link rel=\"stylesheet\" href=\"");


            
            #line 10 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
                            Write(Url.Content("~/Content/widget/iview/skin1/style.css"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n    <script src=\"");


            
            #line 11 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
            Write(Url.Content("~/Content/widget/iview/raphael-min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    <script src=\"");


            
            #line 12 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
            Write(Url.Content("~/Content/widget/iview/jquery.easing.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n    <script src=\"");


            
            #line 13 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
            Write(Url.Content("~/Content/widget/iview/iview.js"));

            
            #line default
            #line hidden
WriteLiteral(@""" type=""text/javascript""></script>



    <script type=""text/javascript"">
        $(function () {
            $('#navList > li:not(.divider-vertical):eq(3)').addClass('active').siblings().removeClass('active');
            $('#iview').iView({
                pauseTime: 7000,
                directionNav: false,
                controlNav: true,
                tooltipY: -15
            });            $('.datepicker').datepicker();
        });
    </script>
");


});

WriteLiteral("\r\n\r\n");


DefineSection("LeftBanner", () => {

WriteLiteral("\r\n            <div class=\"row-fluid well span12 alert alert-info\">\r\n\t\t\t\t");



WriteLiteral(@"
				&emsp;您可以选择某一段时段的我
                <div class=""input-prepend input-append date datepicker"" id=""dp3"" data-date=""12-02-2012""  data-date-viewmode=""years""  data-date-minviewmode=""months"" data-date-format=""mm/yyyy"">
                    <span class=""add-on"">开始时间</span>
                    <input class=""span8"" size=""16"" type=""text"" value=""01/2013"" readonly>
                    <span class=""add-on""><i class=""icon-calendar""></i></span>
                </div>
                <div class=""input-prepend input-append date datepicker"" id=""dp4"" data-date=""12-02-2012""  data-date-viewmode=""years""  data-date-minviewmode=""months"" data-date-format=""mm/yyyy"">
                    <span class=""add-on"">结束时间</span>
                    <input class=""span8"" size=""16"" type=""text"" value=""01/2013"" readonly>
                    <span class=""add-on""><i class=""icon-calendar""></i></span>
                </div>
			</div>
    <div class=""row-fluid"">
	    <div class=""well span12"">
            <div class=""alert alert-info alert-block"">
				<a class=""close"" data-dismiss=""alert"" href=""#"">&times;</a>
				<h6 class=""alert-heading"">您可以选择某一段时段的我</h6>
");



WriteLiteral("\r\n\t\t\t</div>\r\n\t\t    <div class=\"input-prepend input-append date datepicker\" id=\"dp" +
"3\" data-date=\"12-02-2012\"  data-date-viewmode=\"years\"  data-date-minviewmode=\"mo" +
"nths\" data-date-format=\"mm/yyyy\">\r\n                <span class=\"add-on\">开始时间</sp" +
"an>\r\n                <input class=\"span8\" size=\"16\" type=\"text\" value=\"01/2013\" " +
"readonly>\r\n                <span class=\"add-on\"><i class=\"icon-calendar\"></i></s" +
"pan>\r\n            </div>\r\n            <div class=\"input-prepend input-append dat" +
"e datepicker\" id=\"dp4\" data-date=\"12-02-2012\"  data-date-viewmode=\"years\"  data-" +
"date-minviewmode=\"months\" data-date-format=\"mm/yyyy\">\r\n                <span cla" +
"ss=\"add-on\">结束时间</span>\r\n                <input class=\"span8\" size=\"16\" type=\"te" +
"xt\" value=\"01/2013\" readonly>\r\n                <span class=\"add-on\"><i class=\"ic" +
"on-calendar\"></i></span>\r\n            </div>\r\n\t    </div><!--/.well -->\r\n    </d" +
"iv>\r\n    <div class=\"row-fluid well span12 alert alert-info\">\r\n        筛选照片\r\n   " +
"     <div class=\"input-prepend input-append dropdown combobox\">\r\n            <sp" +
"an class=\"add-on\">相册分类</span>\r\n\t\t\t<input class=\"span6\" type=\"text\">\r\n\t\t\t<button " +
"class=\"btn\" data-toggle=\"dropdown\"><i class=\"caret\"></i></button>\r\n\t\t\t<ul class=" +
"\"dropdown-menu\">\r\n\t\t\t\t<li data-value=\"1\" data-foo=\"bar\"><a href=\"#\">正式</a></li>\r" +
"\n\t\t\t\t<li data-value=\"2\"><a href=\"#\">生活</a></li>\r\n\t\t\t\t<li data-value=\"3\" data-sel" +
"ected=\"true\"><a href=\"#\">工作</a></li>\r\n\t\t\t\t<li data-value=\"4\" data-fizz=\"buzz\"><a" +
" href=\"#\">学习</a></li>\r\n\t\t\t</ul>\r\n\t\t</div>    \r\n    </div>\r\n    <div class=\"row-f" +
"luid well span12 alert alert-info\">\r\n        照片标签\r\n        <div class=\"pillbox w" +
"ell\">\r\n\t\t\t<span class=\"label label-info\">信息</span>\r\n            <span class=\"lab" +
"el label-info\">信息</span>\r\n            <span class=\"label label-info\">信息</span>\r\n" +
"\t\t</div>    \r\n    </div>\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("BreadCrumb", () => {

WriteLiteral("\r\n    <div class=\"span12\">\r\n        <ul class=\"breadcrumb\">\r\n            <li>\r\n  " +
"              <a href=\"#\">相册</a>\r\n            </li>\r\n        </ul>\r\n    </div>\r\n" +
"");


});

WriteLiteral("\r\n\r\n<div class=\"container\">\r<div id=\"iview\">\r\n\t\t\t<div data-iview:image=\"");


            
            #line 110 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
                     Write(Url.Content("~/Content/photos/photo9.jpg"));

            
            #line default
            #line hidden
WriteLiteral(@""" data-iview:transition=""slice-top-fade,slice-right-fade"">
				<div class=""iview-caption caption1"" data-x=""80"" data-y=""200"">iView<sup>&trade;</sup></div>
				<div class=""iview-caption"" data-x=""80"" data-y=""275"" data-transition=""wipeRight"">The world's most awesome jQuery Image & Content Slider</div>
				<div class=""iview-caption"" data-x=""254"" data-y=""320"" data-transition=""wipeLeft""><i>Presented by <b>Hemn Chawroka</b></i></div>
			</div>

			<div data-iview:image=""");


            
            #line 116 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
                     Write(Url.Content("~/Content/photos/photo8.jpg"));

            
            #line default
            #line hidden
WriteLiteral(@""" data-iview:transition=""zigzag-drop-top,zigzag-drop-bottom"" data-iview:pausetime=""3000"">
				<div class=""iview-caption caption5"" data-x=""60"" data-y=""280"" data-transition=""wipeDown"">Captions can be positioned and resized freely</div>
				<div class=""iview-caption caption6"" data-x=""300"" data-y=""350"" data-transition=""wipeUp""><a href=""#"">Example URL-link</a></div>
			</div>

			<div data-iview:image=""");


            
            #line 121 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
                     Write(Url.Content("~/Content/photos/photo7.jpg"));

            
            #line default
            #line hidden
WriteLiteral(@""" data-iview:type=""video"" data-iview:transition=""strip-right-fade,strip-left-fade"">
				<iframe src=""http://player.vimeo.com/video/11475955?byline=1&amp;portrait=0"" width=""100%"" height=""100%"" frameborder=""0"" webkitAllowFullScreen mozallowfullscreen allowFullScreen></iframe>
				<div class=""iview-caption caption2"" data-x=""450"" data-y=""340"" data-transition=""wipeRight"">Video</div>
				<div class=""iview-caption caption3"" data-x=""600"" data-y=""345"" data-transition=""wipeLeft"">Support</div>
			</div>

			<div data-iview:image=""");


            
            #line 127 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
                     Write(Url.Content("~/Content/photos/photo9.jpg"));

            
            #line default
            #line hidden
WriteLiteral(@""">
				<div class=""iview-caption caption4"" data-x=""50"" data-y=""80"" data-width=""312"" data-transition=""fade"">Some of iView's Options:</div>
				<div class=""iview-caption blackcaption"" data-x=""50"" data-y=""135"" data-transition=""wipeLeft"" data-easing=""easeInOutElastic"">Touch swipe for iOS and Android devices</div>
				<div class=""iview-caption blackcaption"" data-x=""50"" data-y=""172"" data-transition=""wipeLeft"" data-easing=""easeInOutElastic"">Image And Thumbs Fully Resizable</div>
				<div class=""iview-caption blackcaption"" data-x=""50"" data-y=""209"" data-transition=""wipeLeft"" data-easing=""easeInOutElastic"">Customizable Transition Effect</div>
				<div class=""iview-caption blackcaption"" data-x=""50"" data-y=""246"" data-transition=""wipeLeft"" data-easing=""easeInOutElastic"">Freely Positionable and Stylable Captions</div>
				<div class=""iview-caption blackcaption"" data-x=""50"" data-y=""283"" data-transition=""wipeLeft"" data-easing=""easeInOutElastic"">Cross Browser Compatibility!</div>
			</div>

			<div data-iview:image=""");


            
            #line 136 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
                     Write(Url.Content("~/Content/photos/photo8.jpg"));

            
            #line default
            #line hidden
WriteLiteral(@""">
				<div class=""iview-caption caption7"" data-x=""0"" data-y=""0"" data-width=""180"" data-height=""480"" data-transition=""wipeRight""><h3>The Responsive Caption</h3>This is the product that you <b><i>all have been waiting for</b></i>!<br><br>Customize this slider with just a little HTML and CSS to your very needs. Give each slider some captions to transport your message.<br><br>All in all it works on every browser (including IE6 / 7 / 8) and on iOS and Android devices!</div>
			</div>

			<div data-iview:image=""");


            
            #line 140 "E:\VS2012\MSpace\MSpace\Views\Home\Gallary.cshtml"
                     Write(Url.Content("~/Content/photos/photo7.jpg"));

            
            #line default
            #line hidden
WriteLiteral(@""">
				<div class=""iview-caption caption5"" data-x=""60"" data-y=""150"" data-transition=""wipeLeft"">What are you waiting for?</div>
				<div class=""iview-caption caption6"" data-x=""160"" data-y=""230"" data-transition=""wipeRight"">Get it Now!</div>
			</div>
		</div>    </div>
");


        }
    }
}
