#pragma checksum "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "3E41385D12172D43433FBE3DD207F772F4CB9499"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    
    
    public class _Page_Areas_Admin_Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden

        
        public _Page_Areas_Admin_Views_Home_Index_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

            
            #line 1 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
  
    ViewBag.Title = "后台管理";


            
            #line default
            #line hidden
WriteLiteral("    ");



WriteLiteral("\r\n    ");



WriteLiteral(@"
        <div class=""metro span12"">
            <div class=""metro-sections"">

                <div id=""section1"" class=""metro-section tile-span-4"">
                        <h2>文章管理</h2>
                        <a class=""tile wide imagetext bg-color-blueDark"" href=""./tiles-templates.html"">
                            <div class=""image-wrapper"">
                                ");



WriteLiteral(@"
                                <span class=""icon icon-weather""></span>
                            </div>
                            <div class=""column-text"">
                                <div class=""text4"">
                                    <ul class=""unstyled"">
                                        <li><div data-icon=""&#xe22d;""> 小雨转阴</div></li>
                                        <li><div data-icon=""&#xe21a;""> 0 - 10摄氏度</div></li>
                                        <li><div data-icon=""&#xe219;""> 东西南北风</div></li>
                                        ");



WriteLiteral("\r\n                                    </ul> \r\n                                </d" +
"iv>\r\n                            </div>\r\n                        <div class=\"app" +
"-label\">\r\n                           ");



WriteLiteral("   IP地址\r\n                        </div>\r\n                    </a>\r\n              " +
"      <a class=\"tile wide imagetext wideimage bg-color-orange\" href=\"");


            
            #line 32 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                                              Write(Url.RouteUrl(new { controller = "Article", action = "Write" }));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <img src=\"");


            
            #line 33 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                             Write(Url.Content("~/Content/admin/images/bigTile.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" alt=""""/>
                        <div class=""textover-wrapper bg-color-blue"">
                            <div class=""text2"">
                                写日志
                            </div>
                        </div>
                    </a>
                    <a class=""tile imagetext wide bg-color-greenDark"" href=""");


            
            #line 40 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                                       Write(Url.Action("Index", "Twitter"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <div class=\"image-wrapper\">\r\n                        " +
"    ");



WriteLiteral(@"
                            <span class=""icon icon-coffee""></span>
                        </div>
                        <div class=""column-text"">
                            <div class=""text"">
                                <span data-icon=""&#x0077;""></span> 碎语
                            </div>
                            <div class=""text"">
                                <span data-icon=""&#x0077;""></span> 碎语
                            </div>
                            <div class=""text"">
                                <span data-icon=""&#x0077;""></span> 碎语
                            </div>
                            <div class=""text"">
                                <span data-icon=""&#x0077;""></span> 碎语
                            </div>
                        </div>
                        <div class=""app-label"">
                            碎语
                        </div>
                    </a>
                    <a class=""tile image bg-color-greenDark"" href=""");


            
            #line 63 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                              Write(Url.Action("Index", "NewsExpress"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <div class=\"image-wrapper\">\r\n                        " +
"    <img src=\"");


            
            #line 65 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                 Write(Url.Content("~/Content/admin/images/bigTile1.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" alt=""""/>
                        </div>
                        <div class=""app-label"">
                            新闻速递
                        </div>
                    </a>
                    <a class=""tile square text tilesquareblock"" href=""#"">
                        <div class=""text-header"">日历</div>
                        <div class=""text"">");


            
            #line 73 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                     Write(DateTime.Now.ToString("yyyy年MM月dd日"));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n                    </a>\r\n                    <a class=\"tile app bg-color" +
"-gray\" href=\"");


            
            #line 75 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                       Write(Url.RouteUrl(new { controller = "Article", action = "Index" }));

            
            #line default
            #line hidden
WriteLiteral(@""">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-list-2""></span>
                        </div>
                        <span class=""app-label"">所有日志</span>
                    </a>
                    <a class=""tile app bg-color-red"" href=""");


            
            #line 81 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                      Write(Url.RouteUrl(new { controller = "Rss", action = "Index" }));

            
            #line default
            #line hidden
WriteLiteral(@""">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-rss-2""></span>
                        </div>
                        <span class=""app-label"">RSS订阅管理</span>
                    </a>
                    <a class=""tile app bg-color-yellow"" href=""./images.html"">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-images""></span>
                        </div>
                        <span class=""app-label"">草稿</span>
                    </a>
                    <a class=""tile app bg-color-blueDark"" href=""");


            
            #line 93 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                           Write(Url.RouteUrl(new { controller = "Gallary", action = "Index" }));

            
            #line default
            #line hidden
WriteLiteral(@""">
                     <div class=""image-wrapper"">
                        <span class=""icon icon-images"" ></span>
                     </div>
                     <span class=""app-label"">相册</span>
                    </a>
                    <a class=""tile app bg-color-yellow"" href=""");


            
            #line 99 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                         Write(Url.RouteUrl(new { controller = "ArticleCategory", action = "Index" }));

            
            #line default
            #line hidden
WriteLiteral(@""">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-images""></span>
                        </div>
                        <span class=""app-label"">分类</span>
                    </a>
                    <a class=""tile app bg-color-blueDark"" href=""");


            
            #line 105 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                           Write(Url.RouteUrl(new { controller = "Tag", action = "Index" }));

            
            #line default
            #line hidden
WriteLiteral(@""">
                     <div class=""image-wrapper"">
                        <span class=""icon icon-IcoMoon"" ></span>
                     </div>
                     <span class=""app-label"">标签</span>
                    </a>
                    <a class=""tile app bg-color-red"" href=""");


            
            #line 111 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                      Write(Url.Action("Index", "SiteNews"));

            
            #line default
            #line hidden
WriteLiteral(@""">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-newspaper""></span>
                        </div>
                        <span class=""app-label"">站点新闻</span>
                    </a>
                </div>

                <div id=""section2"" class=""metro-section tile-span-3"">
                    <h2>拓展功能</h2>
                    <a class=""tile app bg-color-red"" href=""");


            
            #line 121 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                      Write(Url.Action("Index", "Remind"));

            
            #line default
            #line hidden
WriteLiteral(@""">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-alert""></span>
                        </div>
                        <div class=""app-label"">提醒</div>
                        <div class=""app-count"">12</div>
                    </a>
                    <a class=""tile app"" href=""");


            
            #line 128 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                         Write(Url.Action("Index", "PrivateMessage"));

            
            #line default
            #line hidden
WriteLiteral(@""">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-chat""></span>
                        </div>
                        <div class=""app-label"">私信</div>
                        <div class=""app-count"">12</div>
                    </a>
                    <a class=""tile app bg-color-yellow"" href=""#"">
                        <div class=""image-wrapper"">
                           <span class=""icon icon-comments-4""></span>
                        </div>
                        <div class=""app-label"">评论</div>
                        <div class=""app-count"">12</div>
                    </a>
                    <a class=""tile app bg-color-yellow"" href=""");


            
            #line 142 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                         Write(Url.Action("Index", "Calendar"));

            
            #line default
            #line hidden
WriteLiteral(@""">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-calendar-alt-stroke""></span>
                        </div>
                        <span class=""app-label"">日历</span>
                    </a>
                    <a class=""tile app bg-color-red"" href=""");


            
            #line 148 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                      Write(Url.Action("Index", "Contact"));

            
            #line default
            #line hidden
WriteLiteral(@""">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-card""></span>
                        </div>
                        <span class=""app-label"">联系人</span>
                    </a>
                    <a class=""tile app bg-color-pink"" href=""./images.html"">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-mail""></span>
                        </div>
                        <span class=""app-label"">邮箱</span>
                    </a> 
                    <a class=""tile app bg-color-blue"" href=""");


            
            #line 160 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                       Write(Url.RouteUrl(new { controller = "Link", action = "Index" }));

            
            #line default
            #line hidden
WriteLiteral(@""">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-link-2""></span>
                        </div>
                        <span class=""app-label"">快捷导航</span>
                    </a> 
                    <a class=""tile app bg-color-gray"" href=""./images.html"">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-reddit""></span>
                        </div>
                        <span class=""app-label"">icon-reddit</span>
                    </a>  
                </div>

                <div id=""section3"" class=""metro-section tile-span-3"">
                    <h2>功能</h2>
                    <a class=""tile app bg-color-green"" href=""");


            
            #line 176 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                        Write(Url.RouteUrl(new { controller = "Statistics", action = "Index" }));

            
            #line default
            #line hidden
WriteLiteral(@""""">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-chart""></span>
                        </div>
                        <span class=""app-label"">统计</span>
                    </a>
                    <a class=""tile app bg-color-yellow"" href=""");


            
            #line 182 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                         Write(Url.Action("Index", "Data"));

            
            #line default
            #line hidden
WriteLiteral(@""">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-database""></span>
                        </div>
                        <span class=""app-label"">数据</span>
                    </a>
                    <a class=""tile app bg-color-purple"" href=""");


            
            #line 188 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                         Write(Url.Action("Index", "Sky"));

            
            #line default
            #line hidden
WriteLiteral(@""">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-cloud-3""></span>
                        </div>
                        <span class=""app-label"">云端</span>
                    </a>
                     <a class=""tile app bg-color-green"" href=""");


            
            #line 194 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                         Write(Url.RouteUrl(new { controller = "Component", action = "Index" }));

            
            #line default
            #line hidden
WriteLiteral(@""""">
                        <div class=""image-wrapper"">
                            <span class=""icon icon-puzzle""></span>
                        </div>
                        <span class=""app-label"">侧边栏组件</span>
                    </a>
                </div>

                <div id=""section4"" class=""metro-section tile-span-4"">
                    <h2>相册列表</h2>
                    <a class=""tile wide imagetext bg-color-blue"" href=""./scaffolding.html"">
                        <div class=""image-wrapper"">
                            <img src=""");


            
            #line 206 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                 Write(Url.Content("~/Content/admin/images/bigTile1.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
                        </div>
                        <div class=""column-text"">
                            <div class=""text"">Grid system</div>
                            <div class=""text"">Layouts</div>
                            <div class=""text"">Responsive design</div>
                        </div>
                        <span class=""app-label"">最新</span>
                    </a>
                    <a class=""tile wide imagetext bg-color-blueDark"" href=""./base-css.html"">
                        <div class=""image-wrapper"">
                            <img src=""");


            
            #line 217 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                 Write(Url.Content("~/Content/admin/images/bigTile1.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
                        </div>
                        <div class=""column-text"">
                            <div class=""text"">Typography</div>
                            <div class=""text"">Tables</div>
                            <div class=""text"">Forms</div>
                            <div class=""text"">Buttons</div>
                        </div>
                        <span class=""app-label"">大学</span>
                    </a>
                    <a class=""tile app bg-color-orange"" href=""./components.html"">
                        <div class=""image-wrapper"">
                            <img src=""");


            
            #line 229 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                 Write(Url.Content("~/Content/admin/images/bigTile1.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" alt="""" />
                        </div>
                        <span class=""app-label"">生活</span>
                    </a>
                    <a class=""tile app bg-color-red"" href=""./javascript.html"">
                        <div class=""image-wrapper"">
                            <img src=""");


            
            #line 235 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                 Write(Url.Content("~/Content/admin/images/bigTile1.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" alt="""" />
                        </div>
                        <span class=""app-label"">学习</span>
                    </a>
                </div>
                
                <div id=""section5"" class=""metro-section tile-span-2"">
                    <h2>功能管理</h2>
                        <div class=""tile tile-double bg-color-blue"">
                            <div class=""tile-icon-large"">
                                <img src=""");


            
            #line 245 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                     Write(Url.Content("~/Content/admin/images/bigTile1.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
                            </div>
                            <span class=""tile-label"">网盘</span>
                        </div>
                        <div class=""tile bg-color-blueDark"">
                            <div class=""tile-icon-large"">
                                <img src=""");


            
            #line 251 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                     Write(Url.Content("~/Content/admin/images/bigTile1.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
                            </div>
                            <span class=""tile-label"">数据备份</span>
                        </div>
                        <div class=""tile bg-color-red"">
                            <div class=""tile-icon-large"">
                                <img src=""");


            
            #line 257 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                     Write(Url.Content("~/Content/admin/images/bigTile1.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
                            </div>
                            <span class=""tile-label"">数据导入导出</span>
                        </div>
                        <div class=""tile bg-color-green"">
                            <div class=""tile-icon-large"">
                                <img src=""");


            
            #line 263 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                     Write(Url.Content("~/Content/admin/images/bigTile1.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
                            </div>
                            <span class=""tile-label"">友链</span>
                        </div>
                        <div class=""tile bg-color-yellow"">
                            <div class=""tile-icon-large"">
                                <img src=""");


            
            #line 269 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                     Write(Url.Content("~/Content/admin/images/bigTile1.png"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
                            </div>
                            <span class=""tile-label"">关闭博客</span>
                        </div>
                    </div>
                
                <div id=""section6"" class=""metro-section tile-span-4"">
                    <h2>磁贴示例</h2>
                    <a class=""tile square text tilesquareblock"" href=""#"">
                        <div class=""text-big"">22</div>
                        <div class=""text"">Text field 2</div>
                    </a>
                    <a class=""tile square text"" href=""#"">
                        <div class=""text-header"">Header</div>
                        <div class=""text"">Text field 1</div>
                        <div class=""text"">Text field 2</div>
                        <div class=""text"">Text field 3</div>
                    </a>
                    <a class=""tile square image"" href=""#"">
                        <img src=""");


            
            #line 288 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                             Write(Url.Content("~/Content/admin/images/bigTile1.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"\"/>\r\n                    </a>\r\n                    <a class=\"tile squarepe" +
"ek\" href=\"#\">\r\n                        <img src=\"");


            
            #line 291 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                             Write(Url.Content("~/Content/admin/images/bigTile1.png"));

            
            #line default
            #line hidden
WriteLiteral("\" alt=\"\"/>\r\n                        <div class=\"text-inner\">\r\n                   " +
"         <div class=\"text-header\">Header</div>\r\n                            <div" +
" class=\"text\">Text field 1</div>\r\n                            <div class=\"text\">" +
"Text field 2</div>\r\n                            <div class=\"text\">Text field 3</" +
"div>\r\n                        </div>\r\n                    </a>\r\n                " +
"    <a class=\"tile widepeek\" href=\"#\">\r\n                        <div class=\"tile" +
"-image-wrapper\">\r\n                            <img src=\"http://aozora.github.com" +
"/bootmetro/content/img/tile-wide.jpg\" alt=\"\"/>\r\n                        </div>\r\n" +
"                        <div class=\"text\">Vivamus elementum semper nisi. Aenean " +
"vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vitae, ele" +
"ifend ac, enim.</div>\r\n                    </a>\r\n                    <a class=\"t" +
"ile wide app\" href=\"#\">\r\n                        <div class=\"image-wrapper\">\r\n  " +
"                          <img src=\"http://aozora.github.com/bootmetro/content/i" +
"mg/Windows 8.png\" alt=\"\"/>\r\n                        </div>\r\n                    " +
"    <div class=\"app-label\">AppName</div>\r\n                        <div class=\"ap" +
"p-count\">12</div>\r\n                    </a>\r\n                    <a class=\"tile " +
"wide text\" href=\"#\">\r\n                        <div class=\"text-header\">Header</d" +
"iv>\r\n                        <div class=\"text\">Text field 1</div>\r\n             " +
"           <div class=\"text\">Text field 2</div>\r\n                        <div cl" +
"ass=\"text\">Text field 3</div>\r\n                        <div class=\"text\">Text fi" +
"eld 4</div>\r\n                    </a>\r\n                    <a class=\"tile wide t" +
"ext\" href=\"#\">\r\n                        <div class=\"text-header\">Header</div>\r\n " +
"                       <div class=\"column\">\r\n                            <div cl" +
"ass=\"text\">Text field 1</div>\r\n                            <div class=\"text\">Tex" +
"t field 2</div>\r\n                            <div class=\"text\">Text field 3</div" +
">\r\n                            <div class=\"text\">Text field 4</div>\r\n           " +
"             </div>\r\n                        <div class=\"column\">\r\n             " +
"               <div class=\"text\">Text field 5</div>\r\n                           " +
" <div class=\"text\">Text field 6</div>\r\n                            <div class=\"t" +
"ext\">Text field 7</div>\r\n                            <div class=\"text\">Text fiel" +
"d 8</div>\r\n                        </div>\r\n                    </a>\r\n           " +
"         <a class=\"tile wide text\" href=\"#\">\r\n                           <div cl" +
"ass=\"text-header\">Header</div>\r\n                           <div class=\"column2-l" +
"abel\">\r\n                              <div class=\"text\">label 1</div>\r\n         " +
"                     <div class=\"text\">label 2</div>\r\n                          " +
"    <div class=\"text\">label 3</div>\r\n                              <div class=\"t" +
"ext\">label 4</div>\r\n                           </div>\r\n                         " +
"  <div class=\"column2-text\">\r\n                              <div class=\"text\">Vi" +
"vamus elementum semper nisi</div>\r\n                              <div class=\"tex" +
"t\">Vivamus elementum semper nisi</div>\r\n                              <div class" +
"=\"text\">Vivamus elementum semper nisi</div>\r\n                              <div " +
"class=\"text\">Vivamus elementum semper nisi</div>\r\n                           </d" +
"iv>\r\n                        </a>\r\n                    <a class=\"tile wide image" +
"\" href=\"#\">\r\n                           <img src=\"http://aozora.github.com/bootm" +
"etro/content/img/tile-wide.jpg\" alt=\"\"/>\r\n                        </a>\r\n        " +
"            <a class=\"tile wide image collection\" href=\"#\">\r\n                   " +
"        <img class=\"tile-image-main\" src=\"http://aozora.github.com/bootmetro/con" +
"tent/img/sample1.png\" alt=\"\"/>\r\n                           <div class=\"mini-tile" +
"s\">\r\n                              <img src=\"http://aozora.github.com/bootmetro/" +
"content/img/tile-wide-collection-1.jpg\" alt=\"\"/>\r\n                              " +
"<img src=\"http://aozora.github.com/bootmetro/content/img/tile-wide-collection-2." +
"png\" alt=\"\"/>\r\n                              <img src=\"http://aozora.github.com/" +
"bootmetro/content/img/tile-wide-collection-3.gif\" alt=\"\"/>\r\n                    " +
"          <img src=\"http://aozora.github.com/bootmetro/content/img/tile-wide-col" +
"lection-4.png\" alt=\"\"/>\r\n                           </div>\r\n                    " +
"    </a>\r\n                     <a class=\"tile wide imagetext wideimage\" href=\"#\"" +
">\r\n                           <img src=\"http://aozora.github.com/bootmetro/conte" +
"nt/img/tile-wide.jpg\" alt=\"\"/>\r\n                           <div class=\"textover-" +
"wrapper\">\r\n                              <div class=\"text\">Vivamus elementum sem" +
"per nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, con" +
"sequat vitae, eleifend ac, enim.</div>\r\n                              <div class" +
"=\"text\">Vivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean " +
"leo ligula, porttitor eu, consequat vitae, eleifend ac, enim.</div>\r\n           " +
"                </div>\r\n                        </a>\r\n                    <a cla" +
"ss=\"tile wide imagetext\" href=\"#\">\r\n                           <div class=\"image" +
"-wrapper\">\r\n                              <img src=\"http://aozora.github.com/boo" +
"tmetro/content/img/tile-wide-collection-3.gif\" alt=\"\"/>\r\n                       " +
"    </div>\r\n                           <div class=\"column-text\">\r\n              " +
"                <div class=\"text-header\">Adipisci velit, sed quia non numquam ei" +
"us modi tempora.</div>\r\n                              <div class=\"text\">Vivamus " +
"elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligula, port" +
"titor eu, consequat vitae, eleifend ac, enim.</div>\r\n                           " +
"   <div class=\"text\">Vivamus elementum semper nisi. Aenean vulputate eleifend te" +
"llus. Aenean leo ligula, porttitor eu, consequat vitae, eleifend ac, enim.</div>" +
"\r\n                              <div class=\"text\">Vivamus elementum semper nisi." +
" Aenean vulputate eleifend tellus. Aenean leo ligula, porttitor eu, consequat vi" +
"tae, eleifend ac, enim.</div>\r\n                              <div class=\"text\">V" +
"ivamus elementum semper nisi. Aenean vulputate eleifend tellus. Aenean leo ligul" +
"a, porttitor eu, consequat vitae, eleifend ac, enim.</div>\r\n                    " +
"      </div>\r\n                        </a>\r\n                    <a class=\"tile t" +
"ilewideblockandtext02\" href=\"#\">\r\n                           <div class=\"tile-co" +
"lumn\">\r\n                              <img src=\"http://aozora.github.com/bootmet" +
"ro/content/img/tile-wide.jpg\" alt=\"\"/>\r\n                           </div>\r\n     " +
"                   </a>\r\n                </div>\r\n\r\n            </div>\r\n        <" +
"/div>\r\n            ");



WriteLiteral("\r\n");



WriteLiteral("\r\n\r\n");



WriteLiteral("\r\n\r\n");


DefineSection("LeftFooter", () => {

WriteLiteral("\r\n    <a class=\"win-command\" data-toggle=\"modal\" href=\"#myModal\">\r\n        <span " +
"class=\"win-commandimage win-commandring\">&#xe03e;</span>\r\n        <span class=\"w" +
"in-label\">添加RSS源</span>\r\n    </a>\r\n    <a class=\"win-command\" data-toggle=\"modal" +
"\" href=\"");


            
            #line 413 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                                                Write(Url.Action("Create"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <span class=\"win-commandimage win-commandring\">&#xe03e;</span>\r\n     " +
"   <span class=\"win-label\">添加源(新页面)</span>\r\n    </a>\r\n    <a class=\"win-command\"" +
" href=\"");


            
            #line 417 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                            Write(Url.Action("List"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <span class=\"win-commandimage win-commandring\">&#xe11f;</span>\r\n     " +
"   <span class=\"win-label\">查看所有源</span>\r\n    </a>\r\n    <a class=\"win-command\" hr" +
"ef=\"");


            
            #line 421 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\Home\Index.cshtml"
                            Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <span class=\"win-commandimage win-commandring\">&#xe125;</span>\r\n     " +
"   <span class=\"win-label\">刷新页面</span>\r\n    </a>\r\n");


});

WriteLiteral("\r\n");


DefineSection("RightFooter", () => {

WriteLiteral(@"
    <button class=""win-command"">
        <span class=""win-commandimage win-commandring"">&#xe1cd;</span>
        <span class=""win-label"">Previous</span>
    </button>
    <button class=""win-command"">
        <span class=""win-commandimage win-commandring"">&#xe1ca;</span>
        <span class=""win-label"">Next</span>
    </button>
    <button class=""win-command"">
        <span class=""win-commandimage win-commandring"">&#xe202;</span>
        <span class=""win-label"">设置</span>
    </button>
    <button class=""win-command"">
        <span class=""win-commandimage win-commandring"">&#x0067;</span>
        <span class=""win-label"">搜索</span>
    </button>
");


});


        }
    }
}
