#pragma checksum "E:\VS2012\MSpace\MSpace\Views\Message\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "F82AFA6507445ADF2321C8C96D0CC3F8F3E564E5"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using MSpace.Models;
    
    
    public class _Page_Views_Message_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden

        
        public _Page_Views_Message_Index_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

            
            #line 1 "E:\VS2012\MSpace\MSpace\Views\Message\Index.cshtml"
  
    ViewBag.Title = "Index";


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


DefineSection("LeftBanner", () => {

WriteLiteral("\r\n    <div class=\"row-fluid\">\r\n        <div>\r\n            ");


            
            #line 9 "E:\VS2012\MSpace\MSpace\Views\Message\Index.cshtml"
       Write(Html.Action("Publish"));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n    </div>\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("Scripts", () => {

WriteLiteral("\r\n    <script type=\"text/javascript\" src=\"");


            
            #line 15 "E:\VS2012\MSpace\MSpace\Views\Message\Index.cshtml"
                                   Write(Url.Content("~/Scripts/jsrender.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n");


});

WriteLiteral(@"


<div class=""alert alert-info alert-block"">
    <a id=""refreshMessage"" class=""close""><i class=""icon-refresh""></i></a>
    <h4 class=""alert-heading""><i class=""icon-leaf""></i> <em>留言</em></h4>
    <hr />
    <div id=""messageArea"" class=""alert-body"">
        
    </div>
</div>



<script type=""text/x-jsrender"" id=""messageTemplate"">
    {{for messages}}
        <div class=""media"">
            <a class=""pull-left"" target=""_blank"" href=""#"">
                <img class=""media-object img-rounded"" src=""http://www.gravatar.com/avatar/{{:hash}}.png?s=75&d=monsterid&r=g"" />
            </a>
            <div class=""media-body"">
                ");



WriteLiteral(@"
                <blockquote class=""pull-right"">
                    <p class=""muted"">{{:content}}</p>
                    <span class=""badge"">{{:pubDate}}</span> by <span class=""label label-info"">{{:name}}</span>
                </blockquote>
                ");



WriteLiteral(@"
            </div>
        </div>
        <hr />
    {{/for}}
</script>

<script type=""text/javascript"">
    $(function () {
        //art.dialog({ content: '1111' }).time(2500);
        $('#publishMessage').on('click', function (e) {
            //e.preventDefault();
            var url = '");


            
            #line 54 "E:\VS2012\MSpace\MSpace\Views\Message\Index.cshtml"
                  Write(Url.Action("Publish", "Message"));

            
            #line default
            #line hidden
WriteLiteral("\';\r\n            if ($(\'#sendAsPrivate\').is(\':checked\') == true) {\r\n              " +
"  url = \'");


            
            #line 56 "E:\VS2012\MSpace\MSpace\Views\Message\Index.cshtml"
                  Write(Url.RouteUrl("AdminRoute", new { controller = "PrivateMessage", action = "Publish" }));

            
            #line default
            #line hidden
WriteLiteral(@"';
            }
            
            $.ajax({
                url: url,
                type: 'POST',
                data:  $('#messageForm').serialize(),
                dataType: 'json',
                success: function (data) {
                    $(':input').val('');
                    loadMessage();
                    art.dialog({ content: data.msg }).time(2500);
                },
                beforeSend: function () {
                    //$(this).attr('disabled', 'disabled');
                }
            });
        });

        $('#refreshMessage').on('click', function (e) {
            e.preventDefault();
            loadMessage();
        });

        loadMessage();
    });

    function loadMessage() {
        $.ajax({
            url: '");


            
            #line 85 "E:\VS2012\MSpace\MSpace\Views\Message\Index.cshtml"
             Write(Url.Action("List","Message"));

            
            #line default
            #line hidden
WriteLiteral(@"',
            dataType: 'json',
            success: function (data) {
                $(""#messageArea"").empty();
                var html = $(""#messageTemplate"").render(data);
                //Insert into Container
                $(""#messageArea"").append(html);
                $(this).parent().slideDown('slow');
            },
            beforeSend: function () {
                $(this).parent().slideUp('slow');
            }
        });
    }

</script>
");


        }
    }
}
