#pragma checksum "E:\VS2012\MSpace\MSpace\Views\Global\Component.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "571C7412C2B1F39D90F8ED634B2CEE6A7C7966D0"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using MSpace.Models;
    
    
    public class _Page_Views_Global_Component_cshtml : System.Web.Mvc.WebViewPage<IEnumerable<Component>> {
        
#line hidden

        
        public _Page_Views_Global_Component_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

WriteLiteral("\r\n");


            
            #line 3 "E:\VS2012\MSpace\MSpace\Views\Global\Component.cshtml"
 foreach (var item in Model)
{
            
            #line default
            #line hidden
WriteLiteral("   <div class=\"row-fluid\">\r\n    <div class=\"well span12\">\r\n        <fieldset>\r\n  " +
"          <legend>");


            
            #line 7 "E:\VS2012\MSpace\MSpace\Views\Global\Component.cshtml"
               Write(item.Name);

            
            #line default
            #line hidden
WriteLiteral("</legend>\r\n            <div>");


            
            #line 8 "E:\VS2012\MSpace\MSpace\Views\Global\Component.cshtml"
            Write(Html.Raw(@HttpUtility.HtmlDecode(@item.Content)));

            
            #line default
            #line hidden
WriteLiteral("</div>\r\n        </fieldset>\r\n        <hr />\r\n    </div>\r\n    </div>\r\n");


            
            #line 13 "E:\VS2012\MSpace\MSpace\Views\Global\Component.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
