#pragma checksum "E:\VS2012\MSpace\MSpace\Views\Global\BlogRoll.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "C0D2FE9C5729E3D2905D470A43F369D35AD7E8F8"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using MSpace.Models;
    
    
    public class _Page_Views_Global_BlogRoll_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden

        
        public _Page_Views_Global_BlogRoll_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {
WriteLiteral(@"
<script type=""text/javascript"">
    $(function () {
        $('#myCarousel').carousel({
            interval: 3000,
            pause: 'hover'
        });
        $('#myCarousel img').css({ width: 672, height: 259 });
    });
</script>

<div id=""myCarousel"" class=""carousel slide"">
  ");



WriteLiteral("\r\n  <!-- Carousel items -->\r\n  <div class=\"carousel-inner\">\r\n    <div class=\"acti" +
"ve item\">\r\n        <img src=\"");


            
            #line 21 "E:\VS2012\MSpace\MSpace\Views\Global\BlogRoll.cshtml"
             Write(Url.Content("~/Content/thumb/lumia928.jpg"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
        <div class=""carousel-caption"">
            <h4>诺基亚WP8设备Lumia928</h4>
            <p>
                这款设备会采用4.5英寸OLED显示屏，厚度10.2毫米，比Lumia920更轻更薄，配备铝制机身，800万像素PureView摄像头 （Xenon氙气和LED闪光灯组合）。
            </p>
        </div>
    </div>
    <div class=""item"">
        <img src=""");


            
            #line 30 "E:\VS2012\MSpace\MSpace\Views\Global\BlogRoll.cshtml"
             Write(Url.Content("~/Content/thumb/blog2.jpg"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        <div class=\"carousel-caption\">\r\n            <h4>我的博客系统</h4>\r\n      " +
"      <p>\r\n                从去年12月就开始做了，一直到现在，感觉陷入了一种迷茫，不知道该实现那些功能\r\n            <" +
"/p>\r\n        </div>\r\n    </div>\r\n    <div class=\"item\">\r\n        <img src=\"");


            
            #line 39 "E:\VS2012\MSpace\MSpace\Views\Global\BlogRoll.cshtml"
             Write(Url.Content("~/Content/thumb/dy.jpg"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        <div class=\"carousel-caption\">\r\n            <h4>万善城</h4>\r\n         " +
"   <p>\r\n                丹阳万善城博物馆，呵呵，貌似要修缮了。\r\n            </p>\r\n        </div>\r\n " +
"   </div>\r\n    <div class=\"item\">\r\n        <img src=\"");


            
            #line 48 "E:\VS2012\MSpace\MSpace\Views\Global\BlogRoll.cshtml"
             Write(Url.Content("~/Content/thumb/andriod5.jpg"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        <div class=\"carousel-caption\">\r\n            <h4>Andriod 5</h4>\r\n   " +
"         <p>\r\n                See the andriod 5 .\r\n            </p>\r\n        </d" +
"iv>\r\n    </div>\r\n    <div class=\"item\">\r\n        <img src=\"");


            
            #line 57 "E:\VS2012\MSpace\MSpace\Views\Global\BlogRoll.cshtml"
             Write(Url.Content("~/Content/thumb/firefoxos.jpg"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        <div class=\"carousel-caption\">\r\n            <h4>Firefox OS</h4>\r\n  " +
"          <p>\r\n                Mozilla 公司开发的基于Html5和CSS3的移动操作系统\r\n            </p" +
">\r\n        </div>\r\n    </div>\r\n    <div class=\"item\">\r\n        <img src=\"");


            
            #line 66 "E:\VS2012\MSpace\MSpace\Views\Global\BlogRoll.cshtml"
             Write(Url.Content("~/Content/thumb/wpsformobile.jpg"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n        <div class=\"carousel-caption\">\r\n            <h4>WPS For Mobile</h4>" +
"\r\n            <p>\r\n                金山公司出品，为IOS平台提供的Office工具。\r\n            </p>\r\n" +
"        </div>\r\n    </div>\r\n    <div class=\"item\">\r\n        <img src=\"");


            
            #line 75 "E:\VS2012\MSpace\MSpace\Views\Global\BlogRoll.cshtml"
             Write(Url.Content("~/Content/thumb/gaode.jpg"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
        <div class=""carousel-caption"">
            <h4>高德地图</h4>
            <p>
                高德地图API 是一套应用程序接口。通过API，您可以轻松地在自己的应用中定制强大、快速、轻便的地图功能。
            </p>
            <p>
                本系统将加入高德地图，实现LBS功能，敬请期待。
            </p>
        </div>
    </div>
    <div class=""item"">
        <img src=""");


            
            #line 87 "E:\VS2012\MSpace\MSpace\Views\Global\BlogRoll.cshtml"
             Write(Url.Content("~/Content/thumb/kendoui.jpg"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
        <div class=""carousel-caption"">
            <h4>Kendo UI</h4>
            <p>
                Comprehensive HTML5, JavaScript framework for modern web and mobile app development .
            </p>
            <p>
                We will take it in to our mobile platform , so we can provide better service to you . 
            </p>
        </div>
    </div>
    <div class=""item"">
        <img src=""");


            
            #line 99 "E:\VS2012\MSpace\MSpace\Views\Global\BlogRoll.cshtml"
             Write(Url.Content("~/Content/thumb/xiaoaojianghu.jpg"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
        <div class=""carousel-caption"">
            <h4>新版笑傲江湖</h4>
            <p>
                完全颠覆旧版本的作品
            </p>
        </div>
    </div>
  </div>
  <!-- Carousel nav -->
  <a class=""carousel-control left"" href=""#myCarousel"" data-slide=""prev"">&lsaquo;</a>
  <a class=""carousel-control right"" href=""#myCarousel"" data-slide=""next"">&rsaquo;</a>
</div>");


        }
    }
}
