#pragma checksum "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "C9840D2A686BDCD88F5EB4416803189DC935918A"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    
    
    public class _Page_Areas_Admin_Views_SiteNews_Create_cshtml : System.Web.Mvc.WebViewPage<MSpace.Models.SiteNews> {
        
#line hidden

        
        public _Page_Areas_Admin_Views_SiteNews_Create_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

WriteLiteral("\r\n");


            
            #line 3 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
  
    ViewBag.Title = "Create";


            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n\r\n<script src=\"");


            
            #line 9 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
        Write(Url.Content("~/Scripts/jquery.validate.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n<script src=\"");


            
            #line 10 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
        Write(Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js"));

            
            #line default
            #line hidden
WriteLiteral("\" type=\"text/javascript\"></script>\r\n\r\n");


            
            #line 12 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
 using (Html.BeginForm()) {
    
            
            #line default
            #line hidden
            
            #line 13 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
Write(Html.ValidationSummary(true));

            
            #line default
            #line hidden
            
            #line 13 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
                                 

            
            #line default
            #line hidden
WriteLiteral("    <fieldset>\r\n        <legend><h2>添加站点新闻</h2></legend>\r\n        <br />\r\n       " +
" <div class=\"editor-label\">\r\n            ");


            
            #line 18 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
       Write(Html.LabelFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 21 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
       Write(Html.TextBoxFor(model => model.Title, new { @class = "span6"}));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 22 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.Title));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <div class=\"editor-label\">\r\n            ");


            
            #line 26 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
       Write(Html.LabelFor(model => model.Content));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n        <div class=\"editor-field\">\r\n            ");


            
            #line 29 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
       Write(Html.TextAreaFor(model => model.Content, new { @class = "span6", rows = 10}));

            
            #line default
            #line hidden
WriteLiteral("\r\n            ");


            
            #line 30 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
       Write(Html.ValidationMessageFor(model => model.Content));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </div>\r\n\r\n        <p>\r\n            <input type=\"submit\" class=\"span6 bt" +
"n-primary\" value=\"添加新闻\" />\r\n        </p>\r\n    </fieldset>\r\n");


            
            #line 37 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
}

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


DefineSection("LeftFooter", () => {

WriteLiteral("\r\n    <a class=\"win-command\" data-toggle=\"modal\" href=\"");


            
            #line 41 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Create.cshtml"
                                                Write(Url.Action("Index"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n        <span class=\"win-commandimage win-commandring\">&#xe11c;</span>\r\n     " +
"   <span class=\"win-label\">新闻列表</span>\r\n    </a>\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("RightFooter", () => {

WriteLiteral("\r\n    ");



WriteLiteral("\r\n");


});

WriteLiteral("\r\n");


        }
    }
}
