#pragma checksum "E:\VS2012\MSpace\MSpace\Views\Global\Footer.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "45BE43E34122548E579BAFA0BA56C9F8B33151FF"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using MSpace.Models;
    
    
    public class _Page_Views_Global_Footer_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden

        
        public _Page_Views_Global_Footer_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

            
            #line 1 "E:\VS2012\MSpace\MSpace\Views\Global\Footer.cshtml"
  
    ViewBag.Title = "Footer";
    Layout = null;


            
            #line default
            #line hidden
WriteLiteral("\r\n<fieldset>\r\n    <legend>啊啊啊</legend>\r\n</fieldset>\r\n");


        }
    }
}
