#pragma checksum "E:\VS2012\MSpace\MSpace\Views\Global\FamousWord.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "01D99C0E268F63FA8F0D7047453575418D553575"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using MSpace.Models;
    
    
    public class _Page_Views_Global_FamousWord_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden

        
        public _Page_Views_Global_FamousWord_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

            
            #line 1 "E:\VS2012\MSpace\MSpace\Views\Global\FamousWord.cshtml"
  
    ViewBag.Title = "FamousWord";


            
            #line default
            #line hidden
WriteLiteral("        <blockquote class=\"pull-right\">\r\n            <p>掌握系统的思维创新方法，包括发散性思维和逻辑思维，" +
"应用左脑和右脑协调创新的技巧，提高企业战略创新</p>\r\n            <small>Someone famous <cite title=\"Sour" +
"ce Title\">Source Title</cite></small>\r\n        </blockquote>\r\n");


        }
    }
}
