#pragma checksum "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "AF104755D78DEB1077D987E2EE24211B506B1B57"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    
    
    public class _Page_Areas_Admin_Views_SiteNews_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden

        
        public _Page_Areas_Admin_Views_SiteNews_Index_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

            
            #line 1 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Index.cshtml"
  
    ViewBag.Title = "Index";


            
            #line default
            #line hidden
WriteLiteral("\r\n");


DefineSection("Scripts", () => {

WriteLiteral("\r\n    <link href=\"");


            
            #line 6 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Index.cshtml"
           Write(Url.Content("~/Content/widgets/flexigrid/css/flexigrid.css"));

            
            #line default
            #line hidden
WriteLiteral("\" rel=\"stylesheet\" type=\"text/css\" /> \r\n    <script type=\"text/javascript\" src=\"");


            
            #line 7 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Index.cshtml"
                                   Write(Url.Content("~/Content/widgets/flexigrid/js/flexigrid.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>    \r\n");


});

WriteLiteral(@"

<script type=""text/x-jsrender"" id=""siteNewsTemplate"">
    {{for news}}
        <tr>
            <td>{{:Id}}</td>
            <td>{{:Title}}</td>
            <td>{{:Content}}</td>
            <td>{{:PublishDate}}</td>
            <td><a data-val=""{{:Id}}"" href=""");


            
            #line 17 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Index.cshtml"
                                       Write(Url.Action("Delete"));

            
            #line default
            #line hidden
WriteLiteral("\"><i class=\"icon-remove\"></i></a></td>\r\n        </tr>\r\n    {{/for}}\r\n</script>\r\n\r" +
"\n<div class=\"metro span12\">\r\n    <div class=\"metro-sections\">\r\n        <div id=\"" +
"section1\" class=\"metro-section tile-span-6 well\">\r\n            <table id=\"tbNews" +
"\" class=\"table table-hover table-bordered table-striped\">\r\n                <capt" +
"ion><strong>文章列表</strong><hr /></caption>\r\n                <thead>\r\n            " +
"        <tr>\r\n                        <th>#</th>\r\n                        <th>新闻" +
"标题</th>\r\n                        <th>新闻内容</th>\r\n                        <th>发布日期" +
"</th>\r\n                        <th>操作</th>\r\n                    </tr>\r\n         " +
"       </thead>\r\n                <tbody>\r\n                    \r\n                " +
"</tbody>\r\n                <tfoot>\r\n                    <tr>\r\n                   " +
"     <td colspan=\"4\" style=\"text-align:center;\">\r\n                        <div i" +
"d=\"loading\" class=\"progress progress-indeterminate\">\r\n                          " +
"  <div style=\"margin:0px auto;\" class=\"win-ring small\"></div>\r\n                 " +
"       </div>\r\n                        </td>\r\n                    </tr>\r\n       " +
"         </tfoot>\r\n            </table>\r\n        </div>\r\n        <div id=\"sectio" +
"n2\" class=\"metro-section tile-span-6 well\">\r\n            <div id=\"siteNews\"></di" +
"v>\r\n        </div>\r\n    </div>\r\n</div>\r\n\r\n<div id=\"myModal\" class=\"modal warning" +
" bg-color-blu hide fade\" tabindex=\"-1\" role=\"dialog\" aria-labelledby=\"myModalLab" +
"el\" aria-hidden=\"true\">\r\n    <div class=\"modal-body\">\r\n        <p></p>\r\n    </di" +
"v>\r\n    <div class=\"modal-footer\">\r\n        <button class=\"btn btn-large\" data-d" +
"ismiss=\"modal\">关闭</button>\r\n    </div>\r\n</div>\r\n\r\n\r\n<script type=\"text/javascrip" +
"t\">\r\n    $(function () {\r\n        $(\"#siteNews\").flexigrid({\r\n            url: \"" +
"");


            
            #line 69 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Index.cshtml"
             Write(Url.Action("FlexiGrid"));

            
            #line default
            #line hidden
WriteLiteral("?\" + Date().toLocaleString(),\r\n            dataType: \"json\",\r\n            height:" +
" \"auto\",\r\n            usepager: true,\r\n            nowrap: false,\r\n            m" +
"inwidth: 160,\r\n            title: \"网站新闻汇\",\r\n            showtogglebtn: true,\r\n  " +
"          userp: true,\r\n            rp: 20,\r\n            idProperty: \'Id\',\r\n    " +
"        pagetext: \'当前页数\',\r\n            findtext:\'查找\',\r\n            sortder: \"asc" +
"\",\r\n            sortname: \"Id\",\r\n            method:\'GET\',\r\n            pagestat" +
": \'显示记录从{from}到{to}，总数 {total} 条\',\r\n            nomsg: \'没有符合条件的记录存在\',\r\n         " +
"   errormsg: \'运行错误\',\r\n            hideOnSubmit: true,\r\n            showTableTogg" +
"leBtn: true,\r\n            colModel: [\r\n                { display: \'新闻编号\', name: " +
"\'Id\', sortable: true, align: \'center\' },\r\n                { display: \'新闻标题\', nam" +
"e: \'Title\', sortable: true, align: \'center\' },\r\n                { display: \'新闻内容" +
"\', name: \'Content\', sortable: true, align: \'center\' },\r\n                { displa" +
"y: \'发布日期\', name: \'PublishDate\', sortable: true, align: \'center\' }\r\n            ]" +
",\r\n            //buttons: [\r\n            //    { name: \'Add\', bclass: \'add\', onp" +
"ress: undefined },\r\n            //    { name: \'Delete\', bclass: \'delete\', onpres" +
"s: undefined },\r\n            //    { separator: true }\r\n            //],\r\n      " +
"      searchitems: [\r\n                { display: \'新闻标题\', name: \'Title\' },\r\n     " +
"           { display: \'新闻内容\', name: \'Content\', isdefault: true }\r\n            ]\r" +
"\n        });\r\n\r\n        loadNews();\r\n\r\n        $(\"#tbNews tbody\").delegate(\'a\', " +
"\'click\', function (e) {\r\n            e.preventDefault();\r\n            $.ajax({\r\n" +
"                url: \'");


            
            #line 112 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Index.cshtml"
                 Write(Url.Action("Delete"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                cache: false,
                data: {id:$(this).attr('data-val')},
                dataType: 'json',
                beforeSend: function () {
                },
                success: function (data) {
                    $(""this"").parent().parent().remove();
                    $('#myModal').children('div.modal-body').html('<p style=""text-align:center;"" class=""lead"">' + data.msg + '</p>');
                    $('#myModal').modal('show');
                    loadNews();
                }
            });
        });

        function loadNews() {
            $.ajax({
                url: '");


            
            #line 129 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Index.cshtml"
                 Write(Url.Action("List"));

            
            #line default
            #line hidden
WriteLiteral(@"',
                cache: false,
                dataType: 'json',
                beforeSend: function () {
                    $('#loading').show('fast');
                },
                success: function (data) {
                    $(""#tbNews tbody"").empty();
                    var html = $(""#siteNewsTemplate"").render(data);
                    //Insert into Container
                    $(""#tbNews tbody"").append(html);
                    $('#loading').hide('slow');
                }
            });
        }

    });
</script>

");


DefineSection("LeftFooter", () => {

WriteLiteral("\r\n    <a class=\"win-command\" data-toggle=\"modal\" href=\"");


            
            #line 149 "E:\VS2012\MSpace\MSpace\Areas\Admin\Views\SiteNews\Index.cshtml"
                                                Write(Url.Action("Create"));

            
            #line default
            #line hidden
WriteLiteral(@""">
        <span class=""win-commandimage win-commandring"">&#x0025;</span>
        <span class=""win-label"">添加新闻</span>
    </a>

    <a class=""win-command"" data-toggle=""modal"" href=""#myModal3"">
        <span class=""win-commandimage win-commandring"">&#xe126;</span>
        <span class=""win-label"">错误提示</span>
    </a>

");


});

WriteLiteral("\r\n\r\n");


DefineSection("RightFooter", () => {

WriteLiteral("\r\n    ");



WriteLiteral("\r\n");


});


        }
    }
}
