#pragma checksum "E:\VS2012\MSpace\MSpace\Views\Global\Online.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "8A19DB3CD385D36D67E367A4CC3799BD594E0D9E"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using MSpace.Models;
    
    
    public class _Page_Views_Global_Online_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden

        
        public _Page_Views_Global_Online_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

            
            #line 1 "E:\VS2012\MSpace\MSpace\Views\Global\Online.cshtml"
  
    ViewBag.Title = "Online";


            
            #line default
            #line hidden
WriteLiteral(@"
    <ul class=""nav pull-right"">
        <li class=""dropdown"">
            <a href=""#"" class=""dropdown-toggle"" data-toggle=""dropdown"">欢迎你，常伟华<b class=""caret""></b></a>
            <ul class=""dropdown-menu"">
                <li class=""divider""></li>
		        <li class=""nav-header"">不带图标</li>
		        <li>
                    ");


            
            #line 12 "E:\VS2012\MSpace\MSpace\Views\Global\Online.cshtml"
               Write(Html.RouteLink(
                        linkText: "后台管理",
                        routeName: "AdminRoute",
                        routeValues: new { controller="Home", action="Index" }
                    ));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t        </li>\r\n\t\t        <li>\r\n                    ");


            
            #line 19 "E:\VS2012\MSpace\MSpace\Views\Global\Online.cshtml"
               Write(Html.RouteLink(
                        linkText: "注销登录",
                        routeName: "DefaultRoute",
                        routeValues: new { controller = "Account", action = "Logout" }
                    ));

            
            #line default
            #line hidden
WriteLiteral("\r\n\t\t        </li>\r\n                <li class=\"divider\"></li>\r\n                <li" +
" class=\"nav-header\">带有图标</li>\r\n                <li><a href=\"");


            
            #line 27 "E:\VS2012\MSpace\MSpace\Views\Global\Online.cshtml"
                        Write(Url.RouteUrl("AdminRoute", new { controller = "Home", action = "Index" }));

            
            #line default
            #line hidden
WriteLiteral("\"><i class=\"icon-cog\"></i> 后台管理</a></li>\r\n                <li><a href=\"");


            
            #line 28 "E:\VS2012\MSpace\MSpace\Views\Global\Online.cshtml"
                        Write(Url.RouteUrl("DefaultRoute", new { controller = "Account", action = "Logout" }));

            
            #line default
            #line hidden
WriteLiteral("\"><i class=\"icon-off\"></i> 注销登录</a></li>\r\n            </ul>\r\n        </li>\r\n    <" +
"/ul>\r\n");


        }
    }
}
