#pragma checksum "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml" "{ff1816ec-aa5e-4d10-87f7-6f4963833460}" "30745D3A4ABF485C1188688EAE66B4564CAF34D2"
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP {
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using MSpace.Models;
    
    
    public class _Page_Views_Home_Index_cshtml : System.Web.Mvc.WebViewPage<dynamic> {
        
#line hidden

        
        public _Page_Views_Home_Index_cshtml() {
        }
        
        protected ASP.global_asax ApplicationInstance {
            get {
                return ((ASP.global_asax)(Context.ApplicationInstance));
            }
        }
        
        public override void Execute() {

            
            #line 1 "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml"
  
    ViewBag.Title = "常伟华的博客平台";


            
            #line default
            #line hidden

DefineSection("scripts", () => {

WriteLiteral("\r\n    ");



WriteLiteral("\r\n    <script type=\"text/javascript\">\r\n        $(function () {\r\n            $(\'#n" +
"avList > li:not(.divider-vertical):eq(0)\').addClass(\'active\').siblings().removeC" +
"lass(\'active\');\r\n        });\r\n    </script>\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("Login", () => {

WriteLiteral("\r\n");


            
            #line 15 "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml"
     if (Convert.ToBoolean(ViewData["LoginStatus"]))
    { 
        
            
            #line default
            #line hidden
            
            #line 17 "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml"
   Write(Html.Action("Online", "Global"));

            
            #line default
            #line hidden
            
            #line 17 "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml"
                                        ;
    }
    else 
    {
        
            
            #line default
            #line hidden
            
            #line 21 "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml"
   Write(Html.Action("Outline", "Global"));

            
            #line default
            #line hidden
            
            #line 21 "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml"
                                         ;
    } 

            
            #line default
            #line hidden

});

WriteLiteral("                                                                                 " +
"                           \r\n\r\n\r\n\r\n<script type=\"text/javascript\">\r\n    $(functi" +
"on () {\r\n        $(\'#portlet-demo\').portlet({\r\n            sortable: true,\r\n    " +
"        create: function () {\r\n                //alert(\'created portlet.\');\r\n   " +
"         },\r\n            removeItem: function () {\r\n                alert(\'after" +
" remove\');\r\n            },\r\n            columns: [{\r\n                width: \'100" +
"%\',\r\n                portlets: [{\r\n                    attrs: {\r\n               " +
"         id: \'authorInfo\'\r\n                    },\r\n                    title: fu" +
"nction () {\r\n                        return \'<i class=\"icon-user\"></i>&emsp;作者信息" +
"\';\r\n                    },\r\n                    icon: \'\',\r\n                    c" +
"ontent: {\r\n                        //设置区域内容属性\r\n                        style: {\r" +
"\n                            textAlign:\'center\'\r\n                        },\r\n   " +
"                     type: \'text\',\r\n                        text: \'<div id=\"qrco" +
"de1\"></div>\',\r\n                        beforeShow: function (c) {\r\n\r\n           " +
"             },\r\n                        afterShow: function () {\r\n             " +
"               decorateQRCode();\r\n                        }\r\n                   " +
" }\r\n                    //scripts: [\'loaded-by-portlet.js\']\r\n                }, " +
"{\r\n                    attrs: {\r\n                        id: \'announcement\'\r\n   " +
"                 },\r\n                    title: function () {\r\n                 " +
"       return \'<i class=\"icon-bullhorn\"></i>&emsp;网站公告\';\r\n                    }," +
"\r\n                    icon: \'\',\r\n                    content: {\r\n               " +
"         //设置区域内容属性\r\n                        style: {\r\n                         " +
"   textAlign: \'center\'\r\n                        },\r\n                        type" +
": \'text\',\r\n                        text: \'本站晚上六点之后，开启<a href=\"http://monobook.vi" +
"cp.cc:8008/\">http://monobook.vicp.cc:8008/</>域名进行测试\',\r\n                        b" +
"eforeShow: function (c) {\r\n\r\n                        },\r\n                       " +
" afterShow: function () {\r\n                            \r\n                       " +
" }\r\n                    }\r\n                }, {\r\n                    attrs: {\r\n " +
"                       id: \'urlInfo\'\r\n                    },\r\n                  " +
"  title: function () {\r\n                        return \'<i class=\"icon-globe\"></" +
"i>&emsp;网页信息\';\r\n                    },\r\n                    icon: \'\',\r\n         " +
"           content: {\r\n                        //设置区域内容属性\r\n                     " +
"   style: {\r\n                            textAlign: \'center\'\r\n                  " +
"      },\r\n                        type: \'text\',\r\n                        text: \'" +
"<div id=\"qrcode2\"></div>\',\r\n                        beforeShow: function (c) {\r\n" +
"\r\n                        },\r\n                        afterShow: function () {\r\n" +
"                            $(\'#qrcode2\').MyQRCode({\r\n                          " +
"      encoding: \"UTF-8\",\r                                content: window.locatio" +
"n,\r                                size: \"150x150\"\r\n                            " +
"});\r\n                            decorateQRCode();\r\n                        }\r\n " +
"                   }\r\n                }, {\r\n                    attrs: {\r\n      " +
"                  id: \'urlInfo\'\r\n                    },\r\n                    tit" +
"le: function () {\r\n                        return \'友链\';\r\n                    },\r" +
"\n                    icon: \'ui-icon-link\',\r\n                    content: {\r\n    " +
"                    //设置区域内容属性\r\n                        style: {\r\n              " +
"              \r\n                        },\r\n                        type: \'text\'" +
",\r\n                        text: function () {\r\n                            retu" +
"rn \'<div style=\"margin-left:15px;\"><ol><li><a href=\"http://github.com/changweihu" +
"a\" target=\"_blank\" >Github 我的代码库 </a></li><li><a href=\"http://github.com/cmono\" " +
"target=\"_blank\" >Github 我的代码库(Fork别人的) </a></li><li><a href=\"http://www.cnblogs." +
"com/changweihua\" target=\"_blank\" >CNBLOG 我的博客园 </a></li><li><a href=\"http://www." +
"cnblogs.com/changweihua\" target=\"_blank\" >CSDN(需要下载的可以联系我)</a></li></ul></div>\';" +
"\r\n                            //return $(\'#friendLink\').css({display:\'\'}).html()" +
";\r\n                        },\r\n                        beforeShow: function (c) " +
"{\r\n\r\n                        },\r\n                        afterShow: function () " +
"{\r\n                            \r\n                        }\r\n                    " +
"}\r\n                }]\r\n            }]\r\n        });\r\n\r\n        $(\'.ui-portlet-hea" +
"der\').addClass(\'active\');\r\n\r\n        \r\n        $(\'#qrcode1\').qrcode({\r\n         " +
"   text: \"Changweihua www.cmono.net changweihua@cmono.net changweihua@outlook.co" +
"m\",\r\n            width: \"150\",\r\n            height: \"150\"\r\n        });\r\n\r\n      " +
"  \r\n        \r\n\r\n    });\r\n\r\n    function decorateQRCode() {\r\n        $(\'div[id^=q" +
"rcode] img\').addClass(\'img-polaroid img-circle\');\r\n    }\r\n\r\n</script>\r\n         " +
"                                                                                " +
"                                                    \r\n");


DefineSection("LeftBanner", () => {

WriteLiteral("\r\n\r\n    <div class=\"row-fluid\">\r\n       <div id=\"portlet-demo\" class=\"span12\"></d" +
"iv> \r\n    </div>\r\n    <div class=\"row-fluid\">\r\n       ");


            
            #line 166 "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml"
  Write(Html.Action("Component", "Global"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"row-fluid nav-collapse\">\r\n        <div class=\"accor" +
"dion\" id=\"accordion2\">\r\n            <div class=\"accordion-group\">\r\n             " +
"   <div class=\"accordion-heading\">\r\n                    <a class=\"accordion-togg" +
"le\" data-toggle=\"collapse\" data-parent=\"#accordion2\" href=\"#calendar\">\r\n        " +
"                <i class=\"icon-calendar\"></i> 编程日历\r\n                    </a>\r\n  " +
"              </div>\r\n                <div>\r\n                </div>\r\n           " +
" </div>\r\n            <div class=\"accordion-group\">\r\n                <div class=\"" +
"accordion-heading\">\r\n                    <a class=\"accordion-toggle\" data-toggle" +
"=\"collapse\" data-parent=\"#accordion2\" href=\"#collapseTwo\">\r\n                    " +
"    最新动态\r\n                    </a>\r\n                </div>\r\n                <div" +
" id=\"collapseTwo\" class=\"accordion-body collapse\">\r\n                    <div cla" +
"ss=\"accordion-inner\">\r\n                        目前，中国半数5A级景区门票达到100元，黄山门票10年来由80元" +
"涨至230元。山东曲阜称，与同类景区相比收费较低，仅收150元，不涨票价就丢身价。曲阜的孔庙、孔府和孔林，年收入1.5亿元左右，全部上缴了地方财政，但景区维护成" +
"本从未公开。\r\n                    </div>\r\n                </div>\r\n            </div>\r\n" +
"            <div class=\"accordion-group\">\r\n                <div class=\"accordion" +
"-heading\">\r\n                    <a class=\"accordion-toggle\" data-toggle=\"collaps" +
"e\" data-parent=\"#accordion2\" href=\"#collapseThree\">\r\n                        超生罚" +
"款\r\n                    </a>\r\n                </div>\r\n                <div id=\"co" +
"llapseThree\" class=\"accordion-body collapse\">\r\n                    <div class=\"a" +
"ccordion-inner\">\r\n                        学者杨支柱因生二胎被取消公职，并罚款24万余元。他称，计生罚款以前直接叫超生" +
"罚款，入世后改成“社会抚养费”。根据9省市超生罚款的平均数，全国31个省市每年征收的超生罚款可高达279亿元。其中大城市将该收入上缴财政，而地方则分配混乱，部分" +
"罚款去向成谜。\r\n                    </div>\r\n                </div>\r\n            </div>\r" +
"\n          </div>\r\n    </div>\r\n\r\n    <div class=\"row-fluid\">\r\n        <ul class=" +
"\"nav nav-pills nav-stacked\">\r\n            <li>\r\n            <a href=\"#\">首页</a>\r\n" +
"            </li>\r\n            <li><a href=\"#\">...</a></li>\r\n            <li><a " +
"href=\"#\">...</a></li>\r\n        </ul>\r\n    </div>\r\n\r\n");


});

WriteLiteral("\r\n\r\n");


DefineSection("BreadCrumb", () => {

WriteLiteral("\r\n    <div class=\"span12\">\r\n        <ul class=\"breadcrumb\">\r\n            <li>\r\n  " +
"              <a href=\"#\">首页</a>\r\n            </li>\r\n        </ul>\r\n    </div>\r\n" +
"");


});

WriteLiteral("\r\n\r\n\r\n<div class=\"row-fluid\">\r\n    ");


            
            #line 230 "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml"
Write(Html.Action("BlogRoll", "Global"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n\r\n<div class=\"row-fluid\">\r\n<div class=\"alert alert-info alert-block spa" +
"n6\">\r\n    <a class=\"close\"><i class=\"icon-refresh\"></i></a>\r\n    <h4 class=\"aler" +
"t-heading\"><i class=\"icon-random\"></i> 随机日志</h4>\r\n    <hr />\r\n    <div class=\"sp" +
"an12 alert-body\">\r\n        <ul id=\"articleList\" class=\"unstyled\">\r\n\r\n        </u" +
"l>\r\n    </div>\r\n</div>\r\n\r\n<div class=\"alert alert-info alert-block span6\">\r\n    " +
"<a class=\"close\"><i class=\"icon-refresh\"></i></a>\r\n    <h4 class=\"alert-heading\"" +
"><i class=\"icon-bullhorn\"></i> 最新动态</h4>\r\n    <hr />\r\n    <div class=\"span12 ale" +
"rt-body\">\r\n        <ul id=\"newsList\" class=\"unstyled\">\r\n\r\n        </ul>\r\n    </d" +
"iv>\r\n</div>\r\n\r\n</div>\r\n\r\n<div class=\"row-fluid\">\r\n<div class=\"alert alert-info a" +
"lert-block span6\">\r\n    <a class=\"close\"><i class=\"icon-eye-open\"></i></a>\r\n    " +
"<h4 class=\"alert-heading\"><i class=\"icon-tasks\"></i> 当前任务</h4>\r\n    <hr />\r\n    " +
"<div class=\"span12 alert-body\">\r\n        为了更好的融合移动平台，使用Kendoui进行开发准备中 。添加谷歌地图，初步" +
"实现LBS\r\n    </div>\r\n</div>\r\n\r\n<div class=\"alert alert-info alert-block span6\">\r\n " +
"   <a class=\"close\"><i class=\"icon-refresh\"></i></a>\r\n    <h4 class=\"alert-headi" +
"ng\"><i class=\"icon-user\"></i> 个人简介</h4>\r\n    <hr />\r\n    <div class=\"span12 aler" +
"t-body\">\r\n        \r\n    </div>\r\n</div>\r\n\r\n</div>\r\n\r\n<div class=\"row-fluid\">\r\n<di" +
"v class=\"alert alert-info alert-block span6\">\r\n    <a class=\"close\"><i class=\"ic" +
"on-minus\"></i></a>\r\n    <h4 class=\"alert-heading\"><i class=\"icon-random\"></i> 随机" +
"日志</h4>\r\n    <hr />\r\n    <div class=\"span12 alert-body\">\r\n        \r\n    </div>\r\n" +
"</div>\r\n\r\n<div class=\"alert alert-info alert-block span6\">\r\n    <a class=\"close\"" +
"><i class=\"icon-minus\"></i></a>\r\n    <h4 class=\"alert-heading\"><i class=\"icon-us" +
"er\"></i> 个人简介</h4>\r\n    <hr />\r\n    <div class=\"span12 alert-body\">\r\n        \r\n " +
"   </div>\r\n</div>\r\n\r\n</div>\r\n\r\n<div class=\"row-fluid\">\r\n<div class=\"alert alert-" +
"info alert-block span6\">\r\n    <a class=\"close\"><i class=\"icon-minus\"></i></a>\r\n " +
"   <h4 class=\"alert-heading\"><i class=\"icon-random\"></i> 随机日志</h4>\r\n    <hr />\r\n" +
"    <div class=\"span12 alert-body\">\r\n        \r\n    </div>\r\n</div>\r\n\r\n<div class=" +
"\"alert alert-info alert-block span6\">\r\n    <a class=\"close\"><i class=\"icon-minus" +
"\"></i></a>\r\n    <h4 class=\"alert-heading\"><i class=\"icon-user\"></i> 个人简介</h4>\r\n " +
"   <hr />\r\n    <div class=\"span12 alert-body\">\r\n        \r\n    </div>\r\n</div>\r\n\r\n" +
"</div>\r\n\r\n<div class=\"row-fluid\">\r\n<div class=\"alert alert-success alert-block s" +
"pan12\">\r\n    <h4 class=\"alert-heading\"><i class=\"icon-link\"></i> 友情链接</h4>\r\n    " +
"<hr />\r\n    <div class=\"span12 alert-body\">\r\n        \r\n    </div>\r\n</div>\r\n</div" +
">\r\n\r\n\r\n<script src=\"");


            
            #line 332 "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml"
        Write(Url.Content("~/Scripts/jQuery.tmpl.js"));

            
            #line default
            #line hidden
WriteLiteral(@""" type=""text/javascript""></script>
<script id=""twitterTemplate"" type=""text/x-jquery-tmpl"">
    <li><em>${Content}</em> -- ${PubDate}</li>
</script>
<script id=""articleTemplate"" type=""text/x-jquery-tmpl"">
    <li><em>${Title}</em>--${PubDate}</li>
</script>
<script id=""newsTemplate"" type=""text/x-jquery-tmpl"">
    <li>${PublishDate} ==>> <em>${Content}</em></li>
</script>

<script type=""text/javascript"">
    $(function () {
        $('#calendar').datepicker({
            showWeek: true,
            showButtonPanel: true,
            onSelect: function (date) {
                //选中日期，跳转到改天所写日志页面
                alert(date);
            }
        });

        //$('#twitterDiv').load('");


            
            #line 354 "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml"
                            Write(Url.Action("Twitter", "Global"));

            
            #line default
            #line hidden
WriteLiteral("\');\r\n        LoadData(\'twitterTemplate\', \'twitterList\', \'");


            
            #line 355 "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml"
                                               Write(Url.Action("Twitter", "Global"));

            
            #line default
            #line hidden
WriteLiteral("\');\r\n        LoadData(\'articleTemplate\', \'articleList\', \'");


            
            #line 356 "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml"
                                               Write(Url.Action("Article", "Global"));

            
            #line default
            #line hidden
WriteLiteral("\');\r\n        LoadData(\'newsTemplate\', \'newsList\', \'");


            
            #line 357 "E:\VS2012\MSpace\MSpace\Views\Home\Index.cshtml"
                                         Write(Url.Action("LatestNews", "Global"));

            
            #line default
            #line hidden
WriteLiteral(@"');

        //$('div.alert-block').hover(function () {
        //    $(this).transition({ perspective: 100, rotateX: 30 });
        //}, function () {
        //    $(this).transition({ perspective: 0, rotateX: 0 });
        //});

    });

    function LoadData(template, target, url) {
        $.ajax({
            url: url,
            cache: false,
            beforeSend: function () {
                
            },
            complete: function () {
            },
            success: function (data) {
                $('#' + template + '').tmpl(data).appendTo('#' + target + '');
            }
        });
    }


</script>");


        }
    }
}
