//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18034
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.CodeDom.Compiler.GeneratedCodeAttribute("ASP.NET", "4.0.30319.18034")]
[assembly: System.Security.SecurityRulesAttribute(System.Security.SecurityRuleSet.Level2)]
[assembly: System.Runtime.Versioning.TargetFrameworkAttribute(".NETFramework,Version=v4.0")]

namespace @__ASP {
    
    
    internal class FastObjectFactory_app_web_gremenj3 {
        
        
        #line 1 "c:\\dummy.txt"

        #line default
        #line hidden
        
        
        private FastObjectFactory_app_web_gremenj3() {
        }
        
        static object Create_ASP__Page_Views_Global_CopyRight_cshtml() {
            return new ASP._Page_Views_Global_CopyRight_cshtml();
        }
        
        static object Create_ASP__Page_Views_Global_Component_cshtml() {
            return new ASP._Page_Views_Global_Component_cshtml();
        }
        
        static object Create_ASP__Page_Views_Global_FamousWord_cshtml() {
            return new ASP._Page_Views_Global_FamousWord_cshtml();
        }
        
        static object Create_ASP__Page_Views_Global_Outline_cshtml() {
            return new ASP._Page_Views_Global_Outline_cshtml();
        }
        
        static object Create_ASP__Page_Views_Global_BlogRoll_cshtml() {
            return new ASP._Page_Views_Global_BlogRoll_cshtml();
        }
        
        static object Create_ASP__Page_Views_Global_Header_cshtml() {
            return new ASP._Page_Views_Global_Header_cshtml();
        }
        
        static object Create_ASP__Page_Views_Global_Online_cshtml() {
            return new ASP._Page_Views_Global_Online_cshtml();
        }
        
        static object Create_ASP__Page_Views_Global_Twitter_cshtml() {
            return new ASP._Page_Views_Global_Twitter_cshtml();
        }
        
        static object Create_ASP__Page_Views_Global_Footer_cshtml() {
            return new ASP._Page_Views_Global_Footer_cshtml();
        }
    }
}
